
;;correcoes ADJ para PCP
(-> "válido_ADJ" "válido_PCP" :cr)
(-> "adequado_ADJ" "adequado_PCP" :cr)
(-> "avoado_ADJ" "avoado_PCP" :cr)
(-> "intencionado_ADJ" "intencionado_PCP" :cr)
(-> "Adquirido_ADJ" "Adquirido_PCP" :cr)
(-> "esperado_ADJ" "esperado_PCP" :cr)
(-> "apavorado_ADJ" "apavorado_PCP" :cr)
(-> "pesado_ADJ" "pesado_PCP" :cr)
(-> "sagrado_ADJ" "sagrado_PCP" :cr)
(-> "teleguiado_ADJ" "teleguiado_PCP" :cr)
(-> "privado_ADJ" "privado_PCP" :cr)
(-> "subdesenvolvido_ADJ" "subdesenvolvido_PCP" :cr)
(-> "querido_ADJ" "querido_PCP" :cr)
(-> "dourado_ADJ" "dourado_PCP" :cr)
(-> "renomado_ADJ" "renomado_PCP" :cr)
(-> "colorido_ADJ" "colorido_PCP" :cr)
(-> "prateado_ADJ" "prateado_PCP" :cr)
(-> "comportado_ADJ" "comportado_PCP" :cr)
(-> "incluido_ADJ" "incluido_PCP" :cr)
(-> "letrado_ADJ" "letrado_PCP" :cr)
(-> "esclerosado_ADJ" "esclerosado_PCP" :cr)
(-> "lexotado_ADJ" "lexotado_PCP" :cr)
(-> "escolado_ADJ" "escolado_PCP" :cr)
(-> "apavorado_ADJ" "apavorado_PCP" :cr)
(-> "Alienado_ADJ" "Alienado_PCP" :cr)
(-> "roído_ADJ" "roído_PCP" :cr)
(-> "ferido_ADJ" "ferido_PCP" :cr)
(-> "passado_ADJ" "passado_PCP" :cr)
(-> "armado_ADJ" "armado_PCP" :cr)
(-> "falado_ADJ" "falado_PCP" :cr)
(-> "sincronizado_ADJ" "sincronizado_PCP" :cr)
(-> "computadorizado_ADJ" "computadorizado_PCP" :cr)
(-> "vermelho/amarelado_ADJ" "vermelho/amarelado_PCP" :cr) 
(-> "amarelado_ADJ" "amarelado_PCP" :cr)
(-> "azulado_ADJ" "azulado_PCP" :cr)
(-> "ensandecido_ADJ" "ensandecido_PCP" :cr)
(-> "associado_ADJ" "associado_PCP" :cr)
(-> "oriunda_ADJ" "oriunda_PCP" :cr) 
(-> "pesada_ADJ" "pesada_PCP" :cr) 
(-> "ensolarada_ADJ" "ensolarada_PCP" :cr) 
(-> "computadorizada_ADJ" "computadorizada_PCP" :cr) 
(-> "humorada_ADJ" "humorada_PCP" :cr) 
(-> "nascida_ADJ" "nascida_PCP" :cr) 
(-> "árida_ADJ " "árida_PCP " :cr) 
(-> "suada_ADJ" "suada_PCP" :cr) 
(-> "roída_ADJ" "roída_PCP" :cr) 
(-> "estereotipada_ADJ" "estereotipada_PCP" :cr) 
(-> "lascada_ADJ" "lascada_PCP" :cr) 
(-> "gélida_ADJ" "gélida_PCP" :cr) 
(-> "tórrida_ADJ" "tórrida_PCP" :cr) 
(-> "civilizada_ADJ" "civilizada_PCP" :cr) 
(-> "iluminada_ADJ" "iluminada_PCP" :cr) 
(-> "passada_ADJ" "passada_PCP" :cr) 
(-> "interditada_ADJ" "interditada_PCP" :cr) 
(-> "autogerida_ADJ" "autogerida_PCP" :cr) 
(-> "internacionalizada_ADJ" "internacionalizada_PCP" :cr) 
(-> "animados_ADJ" "animados_PCP" :cr) 
(-> "antecipados_ADJ" "antecipados_PCP" :cr) 
(-> "arrojados_ADJ" "arrojados_PCP" :cr) 
(-> "Associados_ADJ" "Associados_PCP" :cr) 
(-> "auxiliados_ADJ" "auxiliados_PCP" :cr) 
(-> "coloridos_ADJ" "coloridos_PCP" :cr) 
(-> "computadorizados_ADJ" "computadorizados_PCP" :cr) 
(-> "descomprometidos_ADJ" "descomprometidos_PCP" :cr) 
(-> "despreparados_ADJ" "despreparados_PCP" :cr) 
(-> "dourados_ADJ" "dourados_PCP" :cr) 
(-> "efeminados_ADJ" "efeminados_PCP" :cr) 
(-> "entendidos_ADJ" "entendidos_PCP" :cr) 
(-> "estereotipados_ADJ" "estereotipados_PCP" :cr) 
(-> "importados_ADJ" "importados_PCP" :cr) 
(-> "listados_ADJ" "listados_PCP" :cr) 
(-> "pesados_ADJ" "pesados_PCP" :cr) 
(-> "pirateados_ADJ" "pirateados_PCP" :cr) 
(-> "tratados_ADJ" "tratados_PCP" :cr) 
(-> "tutelados_ADJ" "tutelados_PCP" :cr) 
(-> "descoberto_ADJ" "descoberto_PCP" :cr)  
(-> "ocultos_ADJ" "ocultos_PCP" :cr)
(-> "sujeito_ADJ" "sujeito_PCP" :cr)
(-> "suposto_ADJ" "suposto_PCP" :cr) 
(-> "supostos_ADJ" "supostos_PCP" :cr) 
(-> "abandonadas_ADJ" "abandonadas_PCP" :cr) 
(-> "armadas_ADJ" "armadas_PCP" :cr)  
(-> "chacinadas_ADJ" "chacinadas_PCP" :cr) 
(-> "devidas_ADJ" "devidas_PCP" :cr)
(-> "estereotipadas_ADJ" "estereotipadas_PCP" :cr) 
(-> "securitizadas_ADJ" "securitizadas_PCP" :cr) 
(-> "aberta_ADJ" "aberta_PCP" :cr) 
(-> "abertas_ADJ" "abertas_PCP" :cr) 
(-> "dita_ADJ" "dita_PCP" :cr) 
(-> "ditas_ADJ" "ditas_PCP" :cr) 
(-> "morta_ADJ" "morta_PCP" :cr) 
(-> "restritas_ADJ" "restritas_PCP" :cr) 
(-> "solta_ADJ" "solta_PCP" :cr) 
(-> "soltas_ADJ" "soltas_PCP" :cr) 
(-> "sujeita_ADJ" "sujeita_PCP" :cr) 
(-> "vista_ADJ" "vista_PCP" :cr)

;;outras correcoes
(-> "Brando_ADJ" "Brando_NPROP" :cr)
(-> "foi_V o_ART quarto_N colocado_PCP" "foi_V o_ART quarto_ADJ colocado_N" :cr)
(-> "31º_ADJ colocado_PCP" "31º_ADJ colocado_N" :cr)
(-> "bem_PCP *_PCP" "bem_ADV *_ADJ" :cr)
(-> "mal_PCP *_PCP" "mal_ADV *_ADJ" :cr)
(-> "somente_PDEN depois_PREP de_PREP comunicado_PCP oficial_N" "somente_PDEN depois_PREP de_PREP comunicado_N oficial_ADJ" :cr)
(-> "anteontem_ADV soldados_PCP britânicos_N" "anteontem_ADV soldados_N britânicos_ADJ" :cr)
(-> "distante_ADJ e_KC caminhadas_PCP mais_ADV longínquas_ADJ" "distante_ADJ e_KC caminhadas_N mais_ADV longínquas_ADJ" :cr)
(-> "a_ART presente_ADJ medida_PCP provisória_ADJ" "a_ART presente_ADJ medida_N provisória_ADJ" :cr)
(-> "teve_V a_ART maior_ADJ goleada_PCP" "teve_V a_ART maior_ADJ goleada_N" :cr)
(-> "consideram_V críticas_ADJ exageradas_PCP" "consideram_V críticas_N exageradas_ADJ" :cr)
(-> "É_V preciso_ADJ cuidados_PCP antes_ADV de_PREP" "É_V preciso_ADJ cuidados_N antes_ADV de_PREP" :cr)
(-> "serviços_N bancários_ADJ informatizados_PCP" "serviços_N bancários_ADJ informatizados_ADJ" :cr)
(-> "o_ART grande_ADJ homenageado_PCP" "o_ART grande_ADJ homenageado_N" :cr)
(-> "o_ART surpreendente_ADJ verdadeiro_ADJ culpado_PCP" "o_ART surpreendente_ADJ verdadeiro_ADJ culpado_N" :cr)
(-> "a_ART grande_ADJ visada_PCP niilista_N" "a_ART grande_ADJ visada_N niilista_ADJ" :cr)
(-> "maior_ADJ aliada_PCP de_PREP a_ART" "maior_ADJ aliada_N de_PREP a_ART" :cr)
(-> "uma_ART inimiga_ADJ acirrada_PCP" "uma_ART inimiga_N acirrada_ADJ" :dd :cr)
(-> "tradicional_ADJ aliada_PCP de_PREP os_ART sérvios_N"  "tradicional_ADJ aliada_N de_PREP os_ART sérvios_N" :cr)
(-> "três_NUM últimas_ADJ partidas_PCP" "três_NUM últimas_ADJ partidas_N" :cr)
(-> "rodízios_N VAUX_PCP com_PREP" "rodízios_N com_PREP" :cr)
(-> "um_ART mal_N entendido_PCP" "um_ART mal_ADV entendido_N" :cr)
(-> "curta_PREP ADJ_PREP tecido_N listrado_PCP" "curta_ADJ tecido_N listrado_ADJ" :cr)
(-> "vezes_N demasiado_PCP óbvia_ADJ" "vezes_N demasiado_ADV óbvia_ADJ" :cr)
(-> "e_KC rodopiante_N" "e_KC rodopiante_ADJ" :cr)
(-> "mercado_N auto-_N regulado_PCP e_KC" "mercado_N auto-regulado_PCP e_KC" :cr)
(-> "forte_N ruído_PCP eram_VAUX" "forte_ADJ ruído_N eram_VAUX" :cr)
(-> "Presos_PCP são_VAUX" "Presos_N são_VAUX" :cr)
(-> "trágico_N emaranhado_PCP" "trágico_ADJ emaranhado_N" :cr)
(-> "Retirada_PCP de_PREP as_ART tropas_N" "Retirada_N de_PREP as_ART tropas_N" :cr)
(-> "quilômetros_N quadrados_PCP" "quilômetros_N quadrados_ADJ" :cr)
(-> "ser_V enviadas_N datilografadas_PCP" "ser_V enviadas_V datilografadas_PCP" :cr)
(-> "os_ART chamados_N \"\_\" desaparecidos_PCP" "os_ART chamados_V \"\_\" desaparecidos_N" :cr)
(-> "presente_ADJ medida_PCP provisória_ADJ" "presente_ADJ medida_N provisória_ADJ" :cr)
(-> "a_ART retomada_PCP de_PREP" "a_ART retomada_N de_PREP" :cr)
(-> "resultado_PCP de_PREP o_ART" "resultado_N de_PREP o_ART" :cr :dd)
(-> "de_PREP a_ART largada_PCP" "de_PREP a_ART largada_N" :cr)
(-> "Resultado_PCP" "Resultado_N" :cr)
(-> "branquinhos_N e_KC aplicados_PCP" "branquinhos_ADJ e_KC aplicados_ADJ" :cr :mm)
(-> "após_PREP a_ART largada_PCP" "após_PREP a_ART largada_N" :cr)
(-> "obrigado_PCP \!\_\!" "obrigado_IN \!\_\!" :cr)
(-> "cobrou_V fechado_PCP" "cobrou_V fechado_ADV" :cr)
(-> "o_ART vacilante_ADJ e_KC o_ART derrotado_PCP" "o_ART vacilante_N e_KC o_ART derrotado_N" :cr)
(-> "os_ART concentrados_PCP" "os_ART concentrados_N" :cr :dd)
(-> "o_ART envaido_PCP" "o_ART envaido_N" :cr :typo)
(-> "a_ART maior_ADJ goleada_PCP" "a_ART maior_ADJ goleada_N" :cr)
(-> "a_ART goleada_PCP" "a_ART goleada_N" :cr)
(-> "chuta_V cruzado_PCP" "chuta_V cruzado_ADV" :cr :dd)
(-> "que_KS os_PROSUB importados_PCP" "que_KS os_PROSUB importados_N" :cr)
(-> "o_ART integrado_PCP de_PREP" "o_ART integrado_N de_PREP" :cr)
(-> "coletor_N de_PREP dados_V" "coletor_N de_PREP dados_N" :cr)
(-> "\(\_\( saída_PCP \)\_\)" "\(\_\( saída_N \)\_\)" :cr)
(-> "volumes_N de_PREP dados_V" "volumes_N de_PREP dados_N" :cr)
(-> "Para_PREP os_ART esquecidos_PCP" "Para_PREP os_ART esquecidos_ADJ" :cr)
(-> "transferência_N \"\_\" sustentada_PCP" "transferência_N \"\_\" sustentada_ADJ" :cr)
(-> "encontrar_V a_ART \(\_\( o_ART \)\_\) parceira_N \(\_\( o_N \)\_\) sonhada_V \(\_\( o_PCP \)\_\) em_PREP" "encontrar_V a_ART \(\_\( o_ART \)\_\) parceira_N \(\_\( o_ART \)\_\) sonhada_V \(\_\( o_ART \)\_\) em_PREP" :cr :dd)
(-> "os_ART eleitos_PCP de_PREP" "os_ART eleitos_N de_PREP" :cr)
(-> "É_V preciso_ADJ cuidados_PCP" "É_V preciso_V cuidados_N" :cr)
(-> "de_PREP dados_V" "de_PREP dados_N" :cr)
(-> "serifadas_PCP e_KC não_ADV serifadas_V" "serifadas_ADJ e_KC não_ADV serifadas_ADJ" :cr)
(-> "posto_PCP de_PREP gasolina_N" "posto_N de_PREP gasolina_N" :cr)
(-> "imaginação_N corre_V solta_PCP" "imaginação_N corre_V solta_ADV" :cr)
(-> "dados_PCP de_PREP a_ART" "dados_N de_PREP a_ART" :cr)
(-> "namorada_PCP de_PREP Moreno_NPROP" "namorada_N de_PREP Moreno_NPROP" :cr)
(-> "tal_PROSUB uma_ART renovada_PCP" "tal_PROSUB uma_ART renovada_N" :cr)
(-> "o_ART surpreendente_ADJ verdadeiro_ADJ culpado_PCP" "o_ART surpreendente_ADJ verdadeiro_ADJ culpado_N" :cr)
(-> "Comidas_PCP leves_N" "Comidas_N leves_ADJ" :cr)
(-> "inchado_PCP e_KC careca_N" "inchado_ADJ e_KC careca_ADJ" :cr)
(-> "Convidado_PCP de_PREP a_ART" "Convidado_N de_PREP a_ART" :cr)
(-> "outro_PROADJ confederado_PCP" "outro_PROADJ confederado_N" :cr)
(-> "O_ART confederado_PCP" "O_ART confederado_N" :cr)
(-> "resultado_PCP de_PREP a_ART" "resultado_N de_PREP a_ART" :cr)
(-> "grande_ADJ visada_PCP niilista_N" "grande_ADJ visada_N niilista_ADJ" :cr)
(-> "viabilizar_V a_ART retomada_PCP" "viabilizar_V a_ART retomada_N" :cr)
(-> "a_ART retomada_PCP de_PREP" "a_ART retomada_N de_PREP" :cr)
(-> "houve_V retomada_PCP" "houve_V retomada_N" :cr)
(-> "faz_V sentido_PCP" "faz_V sentido_N" :cr)
(-> "empregado_PCP de_PREP Melado_NPROP" "empregado_N de_PREP Melado_NPROP" :cr :dd)
(-> "a_ART bacalhoada_PCP" "a_ART bacalhoada_N" :cr)
(-> "fascinada_PCP e_KC horrorizada_V" "fascinada_PCP e_KC horrorizada_PCP" :cr)
(-> "venial_ADJ são_V pinceladas_PCP" "venial_ADJ são_V pinceladas_N" :cr)
(-> "uma_ART visada_PCP européia_N" "uma_ART visada_N européia_N" :cr)
(-> "alternada_PCP e_KC sucessivamente_ADV" "alternada_ADV e_KC sucessivamente_ADV" :cr)
(-> "caminhadas_PCP mais_ADV longínquas_ADJ" "caminhadas_N mais_ADV longínquas_ADJ" :cr)
(-> "Obrigada_PCP ,_," "Obrigada_IN ,_," :cr)
(-> "Cuidado_PCP com_PREP" "Cuidado_N com_PREP" :cr :dd)
(-> "considerado_V um_ART protegido_PCP" "considerado_V um_ART protegido_N" :cr)
(-> "chibatadas_PCP são_V obrigatórias_ADJ" "chibatadas_N são_V obrigatórias_ADJ" :cr)
(-> "a_ART proposta_PCP" "a_ART proposta_N" :cr)
(-> "Rússia_NPROP uma_ART aliada_PCP" "Rússia_NPROP uma_ART aliada_N" :cr)
(-> "os_ART desempregados_PCP continuarão_VAUX" "os_ART desempregados_N continuarão_VAUX" :cr)
(-> "uma_ART inimiga_ADJ acirrada_PCP" "uma_ART inimiga_N acirrada_ADJ" :cr :mm)
(-> "cinco_NUM antentados_PCP" "cinco_NUM atentados_N" :cr)
(-> "foram_V presos_N e_KC interrogados_PCP" "foram_V presos_V e_KC interrogados_V" :mm :cr)
(-> "Obrigado_PCP \!\_\!" "Obrigado_IN \!\_\!" :cr)
(-> "um_ART \'\_\' surto_PCP" "um_ART \'\_\' surto_N" :cr)
(-> "que_KS os_PROSUB importados_PCP" "que_KS os_PROSUB importados_N" :cr)
(-> "e_KC cruzados_PCP" "e_KC cruzados_N" :cr)
(-> "o_ART maior_ADJ prejudicado_PCP" "o_ART maior_ADJ prejudicado_N" :cr)
(-> "foi_PCP VAUX_PCP a_PREP" "foi_VAUX a_PREP" :cr)
(-> "O_ART candidado_PCP de_PREP o_ART PRONA_NPROP" "O_ART candidato_N de_PREP o_ART PRONA_NPROP" :cr)
(-> "Rio_NPROP é_V resultado_PCP de_PREP" "Rio_NPROP é_V resultado_N de_PREP" :cr)
(-> "por_PREP seus_PROADJ governados_PCP" "por_PREP seus_PROADJ governados_N" :cr)
(-> "bronzeamento_N é_V resultado_PCP de_PREP" "bronzeamento_N é_V resultado_N de_PREP" :cr)
(-> "deputado_PCP Nelson_NPROP" "deputado_N Nelson_NPROP" :cr)
(-> "os_ART chamados_N \"\_\" desaparecidos_PCP" "os_ART chamados_V \"\_\" desaparecidos_N" :cr)
(-> "e_KC desaparecidos_PCP políticos_N" "e_KC desaparecidos_N políticos_ADJ" :cr)
(-> "aliado_PCP político_N de_PREP" "aliado_N político_ADJ de_PREP" :cr)
(-> "mal_PCP colocado_V" "mal_ADV colocado_V" :cr)
(-> "previdência_N privada_PCP" "previdência_N privada_ADJ" :cr)
(-> "bancário_ADJ de_PREP os_ART envolvidos_PCP" "bancário_ADJ de_PREP os_ART envolvidos_N" :cr)
(-> "homeopatia_N de_PREP desinformados_PCP" "homeopatia_N de_PREP desinformados_N" :cr)
(-> "entre_PREP as_ART beneficiadas_PCP" "entre_PREP as_ART beneficiadas_N" :cr)
(-> "de_PREP os_ART feridos_PCP foi_V" "de_PREP os_ART feridos_N foi_V" :cr)
(-> "os_PROSUB similares_ADJ importados_PCP" "os_PROSUB similares_N importados_ADJ" :dd :cr)
(-> "resultado_PCP de_PREP fusão_N" "resultado_N de_PREP fusão_N" :cr)
(-> "entre_PREP os_ART pesquisados_PCP" "entre_PREP os_ART pesquisados_N" :cr)
(-> "O_ART primeiro_ADJ beneficiado_PCP" "O_ART primeiro_ADJ beneficiado_N" :cr)
(-> "assim_ADV ,_, ou_KC assado_PCP" "assim_ADV ,_, ou_KC assado_ADV" :cr)
(-> "grid_N de_PREP largada_PCP" "grid_N de_PREP largada_N" :cr :dd)
(-> "afetado_PCP e_KC caipira_N" "afetado_ADJ e_KC caipira_ADJ" :cr :mm)
(-> "prejudicar_V os_ART aquinhoados_PCP" "prejudicar_V os_ART aquinhoados_N" :cr)
(-> "Obrigado_PCP" "Obrigado_PDEN" :cr)
(-> "a_ART retomada_PCP de_PREP" "a_ART retomada_N de_PREP" :cr)
(-> "aliados_PCP de_PREP o_ART governo_N" "aliados_N de_PREP o_ART governo_N" :cr :dd)
(-> "resultado_PCP de_PREP o_ART cruzamento_N" "resultado_N de_PREP o_ART cruzamento_N" :cr)
(-> "tiveram_V resultado_PCP médio_ADJ" "tiveram_V resultado_N médio_ADJ" :cr)
(-> "por_PREP escrito_PCP" "por_PREP escrito_N" :dd :cr)
(-> "Infectados_PCP chegam_V a_PREP" "Infectados_N chegam_V a_PREP" :cr)
(-> "estuprada_V viva_N ou_KC morta_PCP" "estuprada_V viva_ADJ ou_KC morta_ADJ" :cr :mm)
(-> "um_ART quadriculado_PCP de_PREP" "um_ART quadriculado_N de_PREP" :cr)
(-> "Em_PREP esse_PROADJ sentido_PCP" "Em_PREP esse_PROADJ sentido_N" :cr)
(-> "ver_V com_PREP agrado_PCP" "ver_V com_PREP agrado_N" :cr)
(-> "uma_ART relembrada_PCP em_PREP" "uma_ART relembrada_N em_PREP" :cr)
(-> "muitos_PROSUB escritos_PCP para_PREP" "muitos_PROSUB escritos_N para_PREP" :cr)
(-> "tese_N de_PREP doutorado_PCP" "tese_N de_PREP doutorado_N" :cr)
(-> "deixados_V como_PREP legado_PCP" "deixados_V como_PREP legado_N" :cr)
(-> "o_ART envolvido_PCP é_V" "o_ART envolvido_N é_V" :cr)
(-> "era_V adequado_ADJ a_PREP o_ART caso_N" "era_V adequado_PCP a_PREP o_ART caso_N" :cr)
(-> "Alienado_ADJ ._. Desinformado_PCP" "Alienado_PCP ._. Desinformado_PCP" :cr)
(-> "um_ART preço_N inesperado_ADJ" "um_ART preço_N inesperado_PCP" :cr)
(-> "pesado_PCP de_PREP a_ART faixa-título_N" "pesado_ADJ de_PREP a_ART faixa-título_N" :cr)
(-> "desacertos_N (_( gastos_PCP )_) a_ART inflação_N" "desacertos_N (_( gastos_N )_) a_ART inflação_N" :cr)
(-> "crianças_N abandonadas_ADJ brasileiras_ADJ" "crianças_N abandonadas_PCP brasileiras_ADJ" :cr)
(-> "Atrás_PROADJ" "Atrás_ADV" :cr)
(-> "só_PROADJ" "só_PDEN" :cr)
(-> "cadeirinhas_N ño_PROSUB" "cadeirinhas_N o_ART" :cr)
(-> "mil_NUM ñque_PRO-KS-REL" "mil_NUM que_PRO-KS-REL" :cr)
(-> "juros_N ño_PROSUB" "juros_N o_ART" :cr)
(-> "rapaz_N ñtricolor_N declaradoñ_N" "rapaz_N ñtricolor_ADJ declarado_V" :cr :typo)
(-> "ñonde_V moram_V" "onde_ADV-KS-REL moram_V" :cr)
(-> "ñou_N melhor_ADJ ,_, olheirasñ_N" "ou_KC melhor_ADJ ,_, olheiras_N" :cr)
(-> "ñsua_ADJ colega_N" "sua_PROADJ colega_N" :cr)
(-> "ñalternadamenteñ_N por_PREP" "alternadamente_ADV por_PREP" :cr)
(-> "ñclaroñ_N a_PROADJ" "claro_N a_PROADJ" :cr)
(-> "ñsem_PREP música_N" "sem_PREP música_N" :cr)
(-> "ñnem_KC abundam_V" "nem_KC abundam_V" :cr)
(-> "ñenquanto_N quadriplica_V" "enquanto_KS quadriplica_V" :cr)
(-> "ñdistanteñ_N de_PREP" "distante_N de_PREP" :cr)
(-> "ñentre_V eles_PROPESS um_ART Di_NPROP Cavalcantiñ_NPROP" "entre_V eles_PROPESS um_ART Di_NPROP Cavalcanti_NPROP" :cr)
(-> "ñque_V enfrenta_V ventos_N contra_ADV em_PREP o_ART setor_N cofreñ_N" "que_V enfrenta_V ventos_N contra_ADV em_PREP o_ART setor_N cofre_N" :cr)
(-> "ñmas_N pra_PREP" "mas_N pra_PREP" :cr)
(-> "ñcom_N direção_N" "com_PREP direção_N" :cr)
(-> "ñpasmemñ_N nunca_ADV" "pasmem_V nunca_ADV" :cr)
(-> "ñespecialmente_ADV de_PREP" "especialmente_ADV de_PREP" :cr)
(-> "ñda_N geração_N" "de_PREP a_ART geração_N" :cr)
(-> "ñpor_N que_KS" "por_PREP que_KS" :cr)
(-> "ñdo_N tratamento_N" "de_PREP o_N tratamento_N" :cr)
(-> "NPROP,_," "" :cr)
(r-> "(\\w+)_ART PREP\\|\\+_ART" "\\1_PREP" :cr)
(-> "quorum\\|_N" "quorum_N" :cr)

(r-> "(ADJ|PREP|ADV|VAUX|KC|ART|PROADJ|IN|N|NUM|PROPESS|PROSUB|NPROP|PU|KS|PRO-KS|PRO-KS-REL|ADV-KS|ADV-KS-REL|CUR|V|PCP|PDEN)_(SCONJ|DET|ADJ|PREP|ADV|VAUX|KC|ART|PROADJ|IN|N|NUM|PROPESS|PROSUB|NPROP|PU|KS|PRO-KS|PRO-KS-REL|ADV-KS|ADV-KS-REL|CUR|V|PCP|PDEN)" "" :cr)

(-> ":_:" ":_PU" :mm)
(-> "!_!" "!_PU" :mm)
(-> "?_?" "?_PU" :mm)
(-> ";_;" ";_PU" :mm)
(-> ",_," ",_PU" :mm)
(-> "._." "._PU" :mm)
(-> "..._..." "..._PU" :mm)
(-> "(_(" "\(_PU" :mm)
(-> ")_)" "\)_PU" :mm)
(-> "[_[" "\[_PU" :mm)
(-> "]_]" "\]_PU" :mm)
(-> "{_{" "\{_PU" :mm)
(-> "}_}" "\}_PU" :mm)
(-> "\\\\_\\\\" "\\\\_PU" :mm)
(-> "/_/" "\/_PU" :mm)
(-> "<_<" "\<_PU" :mm)
(-> ">_>" "\>_PU" :mm)
(-> "\"\_\"" "\"_PU" :mm)
(-> "\'\_\'" "\'_PU" :mm)
