
(-> "foi_V o_ART quarto_N colocado_PCP" "foi_V o_ART quarto_ADJ colocado_N" :cr)
(-> "31º_ADJ colocado_PCP" "31º_ADJ colocado_N" :cr)
(-> "bem_PCP *_PCP" "bem_ADV *_ADJ" :cr)
(-> "mal_PCP *_PCP" "mal_ADV *_ADJ" :cr)
(-> "bem_ADV vind*_PCP" "bem-vind*_ADJ" :cr :mm)
(-> "somente_PDEN depois_PREP de_PREP comunicado_PCP oficial_N" "somente_PDEN depois_PREP de_PREP comunicado_N oficial_ADJ" :cr)
(-> "anteontem_ADV soldados_PCP britânicos_N" "anteontem_ADV soldados_N britânicos_ADJ" :cr)
(-> "distante_ADJ e_KC caminhadas_PCP mais_ADV longínquas_ADJ" "distante_ADJ e_KC caminhadas_N mais_ADV longínquas_ADJ" :cr)
(-> "a_ART presente_ADJ medida_PCP provisória_ADJ" "a_ART presente_ADJ medida_N provisória_ADJ" :cr)
(-> "teve_V a_ART maior_ADJ goleada_PCP" "teve_V a_ART maior_ADJ goleada_N" :cr)
(-> "consideram_V críticas_ADJ exageradas_PCP" "consideram_V críticas_N exageradas_ADJ" :cr)
(-> "É_V preciso_ADJ cuidados_PCP antes_ADV de_PREP" "É_V preciso_ADJ cuidados_N antes_ADV de_PREP" :cr)
(-> "serviços_N bancários_ADJ informatizados_PCP" "serviços_N bancários_ADJ informatizados_ADJ" :cr)
(-> "o_ART grande_ADJ homenageado_PCP" "o_ART grande_ADJ homenageado_N" :cr)
(-> "o_ART surpreendente_ADJ verdadeiro_ADJ culpado_PCP" "o_ART surpreendente_ADJ verdadeiro_ADJ culpado_N" :cr)
(-> "a_ART grande_ADJ visada_PCP niilista_N" "a_ART grande_ADJ visada_N niilista_ADJ" :cr)
(-> "maior_ADJ aliada_PCP de_PREP a_ART" "maior_ADJ aliada_N de_PREP a_ART" :cr)
(-> "uma_ART inimiga_ADJ acirrada_PCP" "uma_ART inimiga_N acirrada_ADJ" :dd :cr)
(-> "tradicional_ADJ aliada_PCP de_PREP os_ART sérvios_N"  "tradicional_ADJ aliada_N de_PREP os_ART sérvios_N" :cr)
(-> "três_NUM últimas_ADJ partidas_PCP" "três_NUM últimas_ADJ partidas_N" :cr)
(-> "rodízios_N VAUX_PCP com_PREP" "rodízios_N com_PREP" :cr)
(-> "um_ART mal_N entendido_PCP" "um_ART mal_ADV entendido_N" :cr)
(-> "curta_PREP ADJ_PREP tecido_N listrado_PCP" "curta_ADJ tecido_N listrado_ADJ" :cr)
(-> "vezes_N demasiado_PCP óbvia_ADJ" "vezes_N demasiado_ADV óbvia_ADJ" :cr)
(-> "e_KC rodopiante_N" "e_KC rodopiante_ADJ" :cr)
(-> "mercado_N auto-_N regulado_PCP e_KC" "mercado_N auto-regulado_PCP e_KC" :cr)
(-> "forte_N ruído_PCP eram_VAUX" "forte_ADJ ruído_N eram_VAUX" :cr)
(-> "Presos_PCP são_VAUX" "Presos_N são_VAUX" :cr)
(-> "trágico_N emaranhado_PCP" "trágico_ADJ emaranhado_N" :cr)
(-> "Retirada_PCP de_PREP as_ART tropas_N" "Retirada_N de_PREP as_ART tropas_N" :cr)
(-> "quilômetros_N quadrados_PCP" "quilômetros_N quadrados_ADJ" :cr)
(-> "ser_V enviadas_N datilografadas_PCP" "ser_V enviadas_V datilografadas_PCP" :cr)
(-> "os_ART chamados_N \"\_\" desaparecidos_PCP" "os_ART chamados_V \"\_\" desaparecidos_N" :cr)
(-> "presente_ADJ medida_PCP provisória_ADJ" "presente_ADJ medida_N provisória_ADJ" :cr)
(-> "a_ART retomada_PCP de_PREP" "a_ART retomada_N de_PREP" :cr)
(-> "resultado_PCP de_PREP o_ART" "resultado_N de_PREP o_ART" :cr :dd)
(-> "de_PREP a_ART largada_PCP" "de_PREP a_ART largada_N" :cr)
(-> "tocou_V cruzado_PCP" "tocou_V cruzado_ADV" :cr)
(-> "Resultado_PCP" "Resultado_N" :cr)
(-> "branquinhos_N e_KC aplicados_PCP" "branquinhos_ADJ e_KC aplicados_ADJ" :cr :mm)
(-> "após_PREP a_ART largada_PCP" "após_PREP a_ART largada_N" :cr)
(-> "obrigado_PCP \!\_\!" "obrigado_INTJ \!\_\!" :cr)
(-> "cobrou_V fechado_PCP" "cobrou_V fechado_ADV" :cr)
(-> "o_ART vacilante_ADJ e_KC o_ART derrotado_PCP" "o_ART vacilante_N e_KC o_ART derrotado_N" :cr)
(-> "os_ART concentrados_PCP" "os_ART concentrados_N" :cr :dd)
(-> "o_ART envaido_PCP" "o_ART envaido_N" :cr :typo)
(-> "a_ART maior_ADJ goleada_PCP" "a_ART maior_ADJ goleada_N" :cr)
(-> "a_ART goleada_PCP" "a_ART goleada_N" :cr)
(-> "chuta_V cruzado_PCP" "chuta_V cruzado_ADV" :cr :dd)
(-> "que_KS os_PROSUB importados_PCP" "que_KS os_PROSUB importados_N" :cr)
(-> "Palmeiras_NPROP jogando_V adiantado_PCP" "Palmeiras_NPROP jogando_V adiantado_ADV" :cr :dd)
(-> "jogue_V retrancado_PCP" "jogue_V retrancado_ADV" :cr :dd)
(-> "atuando_V improvisado_PCP" "atuando_V improvisado_ADV" :cr :dd)
; (-> "viseira espelhada_PCP" "viseira_N espelhada_ADJ" :cr)
(-> "jogar_V encostado_PCP" "jogar_V encostado_ADV" :cr :dd)
(-> "o_ART integrado_PCP de_PREP" "o_ART integrado_N de_PREP" :cr)
(-> "coletor_N de_PREP dados_V" "coletor_N de_PREP dados_N" :cr)
(-> "\(\_\( saída_PCP \)\_\)" "\(\_\( saída_N \)\_\)" :cr)
(-> "volumes_N de_PREP dados_V" "volumes_N de_PREP dados_N" :cr)
(-> "Para_PREP os_ART esquecidos_PCP" "Para_PREP os_ART esquecidos_ADJ" :cr)
(-> "transferência_N \"\_\" sustentada_PCP" "transferência_N \"\_\" sustentada_ADJ" :cr)
(-> "encontrar_V a_ART \(\_\( o_ART \)\_\) parceira_N \(\_\( o_N \)\_\) sonhada_V \(\_\( o_PCP \)\_\) em_PREP" "encontrar_V a_ART \(\_\( o_ART \)\_\) parceira_N \(\_\( o_ART \)\_\) sonhada_V \(\_\( o_ART \)\_\) em_PREP" :cr :dd)
(-> "os_ART eleitos_PCP de_PREP" "os_ART eleitos_N de_PREP" :cr)
(-> "É_V preciso_ADJ cuidados_PCP" "É_V preciso_V cuidados_N" :cr)
(-> "de_PREP dados_V" "de_PREP dados_N" :cr)
(-> "serifadas_PCP e_KC não_ADV serifadas_V" "serifadas_ADJ e_KC não_ADV serifadas_ADJ" :cr)
(-> "posto_PCP de_PREP gasolina_N" "posto_N de_PREP gasolina_N" :cr)
(-> "imaginação_N corre_V solta_PCP" "imaginação_N corre_V solta_ADV" :cr)
(-> "dados_PCP de_PREP a_ART" "dados_N de_PREP a_ART" :cr)
(-> "namorada_PCP de_PREP Moreno_NPROP" "namorada_N de_PREP Moreno_NPROP" :cr)
(-> "tal_PROSUB uma_ART renovada_PCP" "tal_PROSUB uma_ART renovada_N" :cr)
(-> "o_ART surpreendente_ADJ verdadeiro_ADJ culpado_PCP" "o_ART surpreendente_ADJ verdadeiro_ADJ culpado_N" :cr)
(-> "Comidas_PCP leves_N" "Comidas_N leves_ADJ" :cr)
(-> "inchado_PCP e_KC careca_N" "inchado_ADJ e_KC careca_ADJ" :cr)
; (-> "e_KC escrava  de_PREP" "e_KC escrava_N de_PREP" :cr)
(-> "Convidado_PCP de_PREP a_ART" "Convidado_N de_PREP a_ART" :cr)
(-> "outro_PROADJ confederado_PCP" "outro_PROADJ confederado_N" :cr)
(-> "O_ART confederado_PCP" "O_ART confederado_N" :cr)
(-> "resultado_PCP de_PREP a_ART" "resultado_N de_PREP a_ART" :cr)
(-> "grande_ADJ visada_PCP niilista_N" "grande_ADJ visada_N niilista_ADJ" :cr)
(-> "viabilizar_V a_ART retomada_PCP" "viabilizar_V a_ART retomada_N" :cr)
(-> "a_ART retomada_PCP de_PREP" "a_ART retomada_N de_PREP" :cr)
(-> "houve_V retomada_PCP" "houve_V retomada_N" :cr)
(-> "faz_V sentido_PCP" "faz_V sentido_N" :cr)
(-> "empregado_PCP de_PREP Melado_NPROP" "empregado_N de_PREP Melado_NPROP" :cr :dd)
(-> "a_ART bacalhoada_PCP" "a_ART bacalhoada_N" :cr)
(-> "fascinada_PCP e_KC horrorizada_V" "fascinada_PCP e_KC horrorizada_PCP" :cr)
(-> "venial_ADJ são_V pinceladas_PCP" "venial_ADJ são_V pinceladas_N" :cr)
(-> "uma_ART visada_PCP européia_N" "uma_ART visada_N européia_N" :cr)
(-> "alternada_PCP e_KC sucessivamente_ADV" "alternada_ADV e_KC sucessivamente_ADV" :cr)
(-> "caminhadas_PCP mais_ADV longínquas_ADJ" "caminhadas_N mais_ADV longínquas_ADJ" :cr)
(-> "Obrigada_PCP ,_," "Obrigada_IN ,_," :cr)
(-> "Cuidado_PCP com_PREP" "Cuidado_N com_PREP" :cr :dd)
(-> "considerado_V um_ART protegido_PCP" "considerado_V um_ART protegido_N" :cr)
(-> "chibatadas_PCP são_V obrigatórias_ADJ" "chibatadas_N são_V obrigatórias_ADJ" :cr)
(-> "a_ART proposta_PCP" "a_ART proposta_N" :cr)
(-> "Rússia_NPROP uma_ART aliada_PCP" "Rússia_NPROP uma_ART aliada_N" :cr)
(-> "os_ART desempregados_PCP continuarão_VAUX" "os_ART desempregados_N continuarão_VAUX" :cr)
(-> "uma_ART inimiga_ADJ acirrada_PCP" "uma_ART inimiga_N acirrada_ADJ" :cr :mm)
(-> "cinco_NUM antentados_PCP" "cinco_NUM atentados_N" :cr)
(-> "foram_V presos_N e_KC interrogados_PCP" "foram_V presos_V e_KC interrogados_V" :mm :cr)
(-> "Obrigado_PCP \!\_\!" "Obrigado_IN \!\_\!" :cr)
(-> "um_ART \'\_\' surto_PCP" "um_ART \'\_\' surto_N" :cr)
(-> "que_KS os_PROSUB importados_PCP" "que_KS os_PROSUB importados_N" :cr)
(-> "e_KC cruzados_PCP" "e_KC cruzados_N" :cr)
(-> "o_ART maior_ADJ prejudicado_PCP" "o_ART maior_ADJ prejudicado_N" :cr)
(-> "foi_PCP VAUX_PCP a_PREP" "foi_VAUX a_PREP" :cr)
(-> "O_ART candidado_PCP de_PREP o_ART PRONA_NPROP" "O_ART candidato_N de_PREP o_ART PRONA_NPROP" :cr)
(-> "Rio_NPROP é_V resultado_PCP de_PREP" "Rio_NPROP é_V resultado_N de_PREP" :cr)
(-> "por_PREP seus_PROADJ governados_PCP" "por_PREP seus_PROADJ governados_N" :cr)
(-> "bronzeamento_N é_V resultado_PCP de_PREP" "bronzeamento_N é_V resultado_N de_PREP" :cr)
(-> "deputado_PCP Nelson_NPROP" "deputado_N Nelson_NPROP" :cr)
(-> "os_ART chamados_N \"\_\" desaparecidos_PCP" "os_ART chamados_V \"\_\" desaparecidos_N" :cr)
; (-> "e_KC desaparecidos_PCP políticos" "e_KC desaparecidos_N políticos" :cr)
(-> "aliado_PCP político_N de_PREP" "aliado_N político_ADJ de_PREP" :cr)
(-> "mal_PCP colocado_V" "mal_ADV colocado_V" :cr)
; (-> "previdência privada_PCP" "previdência_N privada_ADJ" :cr :mm)
(-> "bancário_ADJ de_PREP os_ART envolvidos_PCP" "bancário_ADJ de_PREP os_ART envolvidos_N" :cr)
(-> "homeopatia_N de_PREP desinformados_PCP" "homeopatia_N de_PREP desinformados_N" :cr)
(-> "entre_PREP as_ART beneficiadas_PCP" "entre_PREP as_ART beneficiadas_N" :cr)
(-> "de_PREP os_ART feridos_PCP foi_V" "de_PREP os_ART feridos_N foi_V" :cr)
(-> "os_PROSUB similares_ADJ importados_PCP" "os_PROSUB similares_N importados_ADJ" :dd :cr)
(-> "resultado_PCP de_PREP fusão_N" "resultado_N de_PREP fusão_N" :cr)
(-> "entre_PREP os_ART pesquisados_PCP" "entre_PREP os_ART pesquisados_N" :cr)
(-> "O_ART primeiro_ADJ beneficiado_PCP" "O_ART primeiro_ADJ beneficiado_N" :cr)
(-> "assim_ADV ,_, ou_KC assado_PCP" "assim_ADV ,_, ou_KC assado_ADV" :cr)
(-> "grid_N de_PREP largada_PCP" "grid_N de_PREP largada_N" :cr :dd)
(-> "afetado_PCP e_KC caipira_N" "afetado_ADJ e_KC caipira_ADJ" :cr :mm)
(-> "prejudicar_V os_ART aquinhoados_PCP" "prejudicar_V os_ART aquinhoados_N" :cr)
(-> "Obrigado_PCP" "Obrigado_PDEN" :cr)
(-> "a_ART retomada_PCP de_PREP" "a_ART retomada_N de_PREP" :cr)
(-> "aliados_PCP de_PREP o_ART governo_N" "aliados_N de_PREP o_ART governo_N" :cr :dd)
(-> "resultado_PCP de_PREP o_ART cruzamento_N" "resultado_N de_PREP o_ART cruzamento_N" :cr)
(-> "tiveram_V resultado_PCP médio_ADJ" "tiveram_V resultado_N médio_ADJ" :cr)
(-> "por_PREP escrito_PCP" "por_PREP escrito_N" :dd :cr)
(-> "Infectados_PCP chegam_V a_PREP" "Infectados_N chegam_V a_PREP" :cr)
(-> "estuprada_V viva_N ou_KC morta_PCP" "estuprada_V viva_ADJ ou_KC morta_ADJ" :cr :mm)
(-> "um_ART quadriculado_PCP de_PREP" "um_ART quadriculado_N de_PREP" :cr)
(-> "Em_PREP esse_PROADJ sentido_PCP" "Em_PREP esse_PROADJ sentido_N" :cr)
(-> "ver_V com_PREP agrado_PCP" "ver_V com_PREP agrado_N" :cr)
(-> "uma_ART relembrada_PCP em_PREP" "uma_ART relembrada_N em_PREP" :cr)
(-> "muitos_PROSUB escritos_PCP para_PREP" "muitos_PROSUB escritos_N para_PREP" :cr)
(-> "tese_N de_PREP doutorado_PCP" "tese_N de_PREP doutorado_N" :cr)
(-> "deixados_V como_PREP legado_PCP" "deixados_V como_PREP legado_N" :cr)
(-> "o_ART envolvido_PCP é_V" "o_ART envolvido_N é_V" :cr)
(-> "era_V adequado_ADJ a_PREP o_ART caso_N" "era_V adequado_PCP a_PREP o_ART caso_N" :cr)
(-> "Alienado_ADJ ._. Desinformado_PCP" "Alienado_PCP ._. Desinformado_PCP" :cr)
(-> "um_ART preço_N inesperado_ADJ" "um_ART preço_N inesperado_PCP" :cr)
(-> "pesado_PCP de_PREP a_ART faixa-título_N" "pesado_ADJ de_PREP a_ART faixa-título_N" :cr)
(-> "desacertos_N (_( gastos_PCP )_) a_ART inflação_N" "desacertos_N (_( gastos_N )_) a_ART inflação_N" :cr)
; (-> "52 mil crianças abandonadas_ADJ brasileiras" "52 mil crianças abandonadas_PCP brasileiras" :cr)
(-> "Atrás_PROADJ" "Atrás_ADV" :cr)
(-> "só_PROADJ" "só_PDEN" :cr)

;;MWEs

;;correcoes feitas durante a etapa MWE
(-> "e_KC agora_KC" "e_KC agora_ADV" :cr)
(-> "mas_KC também_KC" "mas_KC também_ADV" :cr)
(-> "não_KC tanto_KC" "não_ADV tanto_ADV" :cr)
(-> "e_KC ora_KC" "e_KC ora_ADV" :cr)
(-> "pois_KC tanto_KC" "pois_KC tanto_ADV" :cr)
(-> "e_KC portanto_KC" "e_KC portanto_ADV" :cr)
(-> "quando_KC não_KC" "quando_ADV não_ADV" :cr)
(-> "e_KC mais_KC" "e_KC mais_ADV" :cr)
(-> "e_KC por_KC" "e_KC por_PREP" :cr)  
(-> "e_KC nem_KC" "e_KC nem_ADV" :cr)  
(-> "e_KC assim_KC" "e_KC assim_ADV" :cr)
(-> "linha_ADV a_ADV linha_ADV" "linha_N a_PREP linha_N" :cr)
(-> "e_KC e_KC" "e_KC e_KC" :typo)
(-> "um_ADV pouco_ADV mais_ADV" "um_ART pouco_ADV mais_ADV" :cr)
(-> "um_ADV pouquinho_ADV mais_ADV" "um_ART pouquinho_ADV mais_ADV" :cr)
(-> "ao_ADV mesmo_ADV tempo_ADV" "ao_PREP mesmo_PROADJ tempo_N" :cr)
(-> "um_ADV pouco_ADV" "um_ART pouco_ADV" :cr)
(-> "mais_ADV para_ADV cima_ADV" "mais_ADV para_PREP cima_ADV" :cr)
(-> "mais_ADV do_ADV que_ADV" "mais_ADV do_PREP que_KS" :cr)
(-> "por_ADV minha_ADV causa_ADV" "por_PREP minha_PROADJ causa_N" :cr)
(-> "o_ADV mais_ADV rapidamente_ADV" "o_ADV mais_ADV rapidamente_ADV" :cr)
(-> "um_ADV tiquinho_ADV mais_ADV" "um_ART tiquinho_ADV mais_ADV" :cr)
(-> "talvez_ADV um_ADV pouco_ADV" "talvez_ADV um_ART pouco_ADV" :cr)
(-> "mais_ADV uma_ADV vez_ADV" "mais_ADV uma_ART vez_N" :cr)
(-> "um_ADV pouco_ADV devagar_ADV" "um_ART pouco_ADV devagar_ADJ" :cr)
(-> "um_ADV pouco_ADV assim_ADV" "um_ART pouco_ADV assim_ADV" :cr)
(-> "Um_ADV pouco_ADV antes_ADV" "Um_ART pouco_ADV antes_ADV" :cr)
(-> "o_ADV mais_ADV possível_ADV" "o_ART mais_ADV possível_ADJ" :cr)
(-> "o_ADV mais_ADV rapidamente_ADV" "o_ART mais_ADV rapidamente_ADV" :cr)
(-> "lá_ADV de_ADV cima_ADV" "lá_ADV de_PREP cima_ADV" :cr)
(-> "de_ADV igual_ADV para_ADV igual_ADV" "de_PREP igual_ADJ para_PREP igual_ADJ" :cr)
(-> "só_ADV por_ADV só_ADV" "só_ADV por_PREP só_ADV" :cr)
(-> "bico-_N de-pena_IN" "bico-de-pena_N" :cr)

;;MWEs equivalentes a ADVs
(-> "de_ADV manhã_ADV" "de_PREP manhã_N" :mm :mwe :misc "MWE=de_manhã|MWEPOS=ADV")      
(-> "ainda_ADV por_ADV cima_ADV" "ainda_ADV por_PREP cima_ADV" :mm :mwe :misc "MWE=ainda_por_cima|MWEPOS=ADV")
(-> "o_ADV quanto_ADV antes_ADV" "o_ART quanto_PREP antes_ADV" :mm :mwe :misc "MWE=o_quanto_antes|MWEPOS=ADV")
(-> "por_ADV acaso_ADV" "por_PREP acaso_N" :mm :mwe :misc "MWE=por_acaso|MWEPOS=ADV") 
(-> "em_ADV frente_ADV" "em_PREP frente_N" :mm :mwe :misc "MWE=em_frente|MWEPOS=ADV") 
(-> "em_ADV vigor_ADV" "em_PREP vigor_N" :mm :mwe :misc "MWE=em_vigor|MWEPOS=ADV")
(-> "de_ADV uma_ADV vez_ADV" "de_PREP uma_ART vez_N" :mm :mwe :misc "MWE=de_uma_vez|MWEPOS=ADV")
(-> "em_ADV diante_ADV" "em_PREP diante_PREP" :mm :mwe :misc "MWE=em_diante|MWEPOS=ADV")   
(-> "ponta_ADV a_ADV ponta_ADV" "ponta_N a_PREP ponta_N" :mm :mwe :misc "MWE=ponta_a_ponta|MWEPOS=ADV")
(-> "mais_ADV ou_ADV menos_ADV" "mais_ADV ou_KC menos_ADV" :mm :mwe :misc "MWE=mais_ou_menos|MWEPOS=ADV") 
(-> "de_ADV cabo_ADV a_ADV rabo_ADV" "de_PREP cabo_N a_PREP rabo_N" :mm :mwe :misc "MWE=|MWEPOS=ADV") 
(-> "de_ADV ponta_ADV a_ADV ponta_ADV" "de_PREP ponta_N a_PREP ponta_N" :mm :mwe :misc "MWE=de_ponta_a_ponta|MWEPOS=ADV") 
(-> "rasteiro_ADV à_ADV esquerda_ADV" "rasteiro_ADJ a_PREP a_ART esquerda_N" :cr :mm :mwe :misc "MWE=rasteiro_à_esquerda|MWEPOS=ADV")
(-> "aí_ADV por_ADV diante_ADV" "aí_ADV por_PREP diante_ADV" :mm :mwe :misc "MWE=aí_por_diante|MWEPOS=ADV")
(-> "assim_ADV por_ADV diante_ADV" "assim_ADV por_PREP diante_ADV" :mm :mwe :misc "MWE=assim_por_diante|MWEPOS=ADV")
(-> "por_ADV diante_ADV" "por_PREP diante_PREP" :mm :mwe :misc "MWE=por_diante|MWEPOS=ADV")
(-> "Frente_ADV a_ADV frente_ADV" "Frente_N a_PREP frente_N" :mm :mwe :misc "MWE=Frente_a_frente|MWEPOS=ADV")  
(-> "à_ADV noite_ADV" "a_PREP a_ART noite_N" :cr :mm :mwe :misc "MWE=a_a_noite|MWEPOS=ADV")  
(-> "a_ADV a_ADV noite_ADV" "a_PREP a_ART noite_N" :mm :mwe :misc "MWE=a_a_noite|MWEPOS=ADV")
(-> "a_ADV a_ADV tarde_ADV" "a_PREP a_ART tarde_N" :mm :mwe :misc "MWE=a_a_tarde|MWEPOS=ADV")
(-> "Nem_ADV de_ADV longe_ADV" "Nem_ADV de_PREP longe_ADV" :mm :mwe :misc "MWE=Nem_de_longe|MWEPOS=ADV") 
(-> "ponto_ADV a_ADV ponto_ADV" "ponto_N a_PREP ponto_N" :mm :mwe :misc "MWE=ponto_a_ponto|MWEPOS=ADV")   
(-> "de_ADV trás_ADV" "de_PREP trás_ADV" :mm :mwe :misc "MWE=de_trás|MWEPOS=ADV")
(-> "para_ADV frente_ADV" "para_PREP frente_N" :mm :mwe :misc "MWE=para_frente|MWEPOS=ADV") 
(-> "de_ADV graça_ADV" "de_PREP graça_N" :mm :mwe :misc "MWE=de_graça|MWEPOS=ADV")
(-> "De_ADV vez_ADV em_ADV quando_ADV" "De_PREP vez_N em_PREP quando_KS" :mm :mwe :misc "MWE=De_vez_em_quando|MWEPOS=ADV")
(-> "de_ADV vez_ADV em_ADV quando_ADV" "de_PREP vez_N em_PREP quando_KS" :mm :mwe :misc "MWE=de_vez_em_quando|MWEPOS=ADV")
(-> "por_ADV sua_ADV vez_ADV" "por_PREP sua_PROADJ vez_N" :mm :mwe :misc "MWE=por_sua_vez|MWEPOS=ADV")   
(-> "a_ADV contragosto_ADV" "a_PREP contragosto_N" :mm :mwe :misc "MWE=a_contragosto|MWEPOS=ADV")
(-> "pra_ADV lá_ADV de_ADV" "pra_PREP lá_ADV de_PREP" :mm :mwe :misc "MWE=pra_lá_de|MWEPOS=ADV") 
(-> "em_ADV breve_ADV" "em_PREP breve_ADV" :mm :mwe :misc "MWE=em_breve|MWEPOS=ADV")   
(-> "De_ADV vez_ADV" "De_PREP vez_N" :mm :mwe :misc "MWE=De_vez|MWEPOS=ADV")  
(-> "Até_ADV Que_ADV Enfim_ADV" "Até_PREP Que_KC Enfim_ADV" :mm :mwe :misc "MWE=|Até_Que_EnfimMWEPOS=ADV")
(-> "de_ADV volta_ADV" "de_PREP volta_N" :mm :mwe :misc "MWE=de_volta|MWEPOS=ADV")   
(-> "lado_ADV a_ADV lado_ADV" "lado_N a_PREP lado_N" :mm :mwe :misc "MWE=lado_a_lado|MWEPOS=ADV")  
(-> "volta_ADV e_ADV meia_ADV" "volta_N e_KC meia_ADJ" :mm :mwe :misc "MWE=volta_e_meia|MWEPOS=ADV")  
(-> "em_ADV primeiro_ADV lugar_ADV" "em_PREP primeiro_ADJ lugar_N" :mm :mwe :misc "MWE=em_primeiro_lugar|MWEPOS=ADV")    
(-> "de_ADV modo_ADV algum_ADV" "de_PREP modo_N algum_PROADJ" :mm :mwe :misc "MWE=de_modo_algum|MWEPOS=ADV") 
(-> "pelo_ADV contrário_ADV" "pelo_PREP contrário_N" :mm :mwe :misc "MWE=pelo_contrário|MWEPOS=ADV")
(-> "de_ADV cima_ADV a_ADV baixo_ADV" "de_PREP cima_ADV a_PREP baixo_ADV" :mm :mwe :misc "MWE=de_cima_a_baixo|MWEPOS=ADV")    
(-> "Cara_ADV a_ADV cara_ADV" "Cara_N a_PREP cara_N" :mm :mwe :misc "MWE=Cara_a_cara|MWEPOS=ADV")   
(-> "um_ADV a_ADV um_ADV" "um_PROSUB a_PREP um_PROSUB" :mm :mwe :misc "MWE=um_a_um|MWEPOS=ADV")
(-> "hoje_ADV em_ADV dia_ADV" "hoje_ADV em_PREP dia_N" :mm :mwe :misc "MWE=hoje_em_dia|MWEPOS=ADV")
(-> "cada_ADV vez_ADV mais_ADV" "cada_PROADJ vez_N mais_ADV" :mm :mwe :misc "MWE=cada_vez_mais|MWEPOS=ADV")
(-> "de_ADV alto_ADV a_ADV baixo_ADV" "de_PREP alto_ADV a_PREP baixo_ADV" :mm :mwe :misc "MWE=de_alto_a_baixo|MWEPOS=ADV")
(-> "o_ADV quanto_ADV antes_ADV" "o_ART quanto_ADV antes_ADV" :mm :mwe :misc "MWE=o_quanto_antes|MWEPOS=ADV")
(-> "passo_ADV a_ADV passo_ADV" "passo_N a_PREP passo_N" :mm :mwe :misc "MWE=passo_a_passo|MWEPOS=ADV")
(-> "aqui_ADV e_ADV ali_ADV" "aqui_ADV e_KC ali_ADV" :mm :mwe :misc "MWE=aqui_e_ali|MWEPOS=ADV")
(-> "em_ADV particular_ADV" "em_PREP particular_N" :mm :mwe :misc "MWE=em_particular|MWEPOS=ADV")
(-> "quase_ADV tanto_ADV quanto_ADV" "quase_ADV tanto_ADV quanto_ADV" :mm :mwe :misc "MWE=quase_tanto_quanto|MWEPOS=ADV")
(-> "por_ADV completo_ADV" "por_PREP completo_N" :mm :mwe :misc "MWE=por_completo|MWEPOS=ADV")
(-> "em_ADV seguida_ADV" "em_PREP seguida_N" :mm :mwe :misc "MWE=em_seguida|MWEPOS=ADV")
(-> "pouco_ADV a_ADV pouco_ADV" "pouco_ADV a_PREP pouco_ADV" :mm :mwe :misc "MWE=pouco_a_pouco|MWEPOS=ADV")
(-> "dos_ADV pés_ADV à_ADV cabeça_ADV" "dos_PREP pés_N à_PREP cabeça_N" :mm :mwe :misc "MWE=dos_pés_a_cabeça|MWEPOS=ADV")
(-> "Às_ADV vezes_ADV" "Às_PREP vezes_N" :mm :mwe :misc "MWE=Às_vezes|MWEPOS=ADV")
(-> "de_ADV cima_ADV para_ADV baixo_ADV" "de_PREP cima_ADV para_PREP baixo_ADV" :mm :mwe :misc "MWE=de_cima_para_baixo|MWEPOS=ADV")
(-> "de_ADV baixo_ADV para_ADV cima_ADV" "de_PREP baixo_ADV para_PREP cima_ADV" :mm :mwe :misc "MWE=de_baixo_para_cima|MWEPOS=ADV")
(-> "por_ADV trás_ADV" "por_PREP trás_ADV" :mm :mwe :misc "MWE=por_trás|MWEPOS=ADV")
(-> "vez_ADV por_ADV outra_ADV" "vez_N por_PREP outra_ADJ" :mm :mwe :misc "MWE=vez_por_outra|MWEPOS=ADV")
(-> "ao_ADV pé_ADV da_ADV letra_ADV" "ao_PREP pé_N da_PREP letra_N" :mm :mwe :misc "MWE=ao_pé_da_letra|MWEPOS=ADV")
(-> "a_ADV céu_ADV aberto_ADV" "a_PREP céu_N aberto_PCP" :mm :mwe :misc "MWE=a_céu_aberto|MWEPOS=ADV")
(-> "ao_ADV ar_ADV livre_ADV" "ao_PREP ar_N livre_ADJ" :mm :mwe :misc "MWE=ao_ar_livre|MWEPOS=ADV")
(-> "de_ADV bom_ADV grado_ADV" "de_PREP bom_ADJ grado_N" :mm :mwe :misc "MWE=de_bom_grado|MWEPOS=ADV")
(-> "por_ADV aí_ADV afora_ADV" "por_PREP aí_ADV afora_ADV" :mm :mwe :misc "MWE=por_aí_afora|MWEPOS=ADV")
(-> "com_ADV bons_ADV olhos_ADV" "com_PREP bons_ADJ olhos_N" :mm :mwe :misc "MWE=com_bons_olhos|MWEPOS=ADV")
(-> "em_ADV geral_ADV" "em_PREP geral_ADJ" :mm :mwe :misc "MWE=em_geral|MWEPOS=ADV")
(-> "de_ADV fato_ADV" "de_PREP fato_N" :mm :mwe :misc "MWE=de_fato|MWEPOS=ADV")
(-> "Em_ADV primeiro_ADV lugar_ADV" "Em_PREP primeiro_ADJ lugar_N" :mm :mwe :misc "MWE=Em_primeiro_lugar|MWEPOS=ADV")
(-> "de_ADV novo_ADV" "de_PREP novo_ADJ" :mm :mwe :misc "MWE=de_novo|MWEPOS=ADV")
(-> "mais_ADV um_ADV pouco_ADV" "mais_ADV um_ART pouco_ADV" :mm :mwe :misc "MWE=mais_um_pouco|MWEPOS=ADV")
(-> "baixo_ADV para_ADV cima_ADV" "baixo_ADV para_PREP cima_ADV" :mm :mwe :misc "MWE=baixo_pra_cima|MWEPOS=ADV")
(-> "nem_ADV ao_ADV menos_ADV" "nem_KC ao_PREP menos_ADV" :mm :mwe :misc "MWE=nem_ao_menos|MWEPOS=ADV")
(-> "De_ADV quando_ADV em_ADV quando_ADV" "De_PREP quando_ADV em_PREP quando_ADV" :mm :mwe :misc "MWE=De_quando_em_quando|MWEPOS=ADV")
(-> "a_ADV olho_ADV nu_ADV" "a_PREP olho_N nu_ADJ" :mm :mwe :misc "MWE=a_olho_nu|MWEPOS=ADV")
(-> "de_ADV quando_ADV em_ADV quando_ADV" "de_PREP quando_ADV em_PREP quando_ADV" :mm :mwe :misc "MWE=de_quando_em_quando|MWEPOS=ADV")
(-> "Por_ADV outro_ADV lado_ADV" "Por_PREP outro_ADJ lado_N" :mm :mwe :misc "MWE=Por_outro_lado|MWEPOS=ADV")
(-> "sem_ADV mais_ADV nem_ADV menos_ADV" "sem_PREP mais_ADV nem_PREP menos_ADV" :mm :mwe :misc "MWE=sem_mais_nem_menos|MWEPOS=ADV")
(-> "Hoje_ADV em_ADV dia_ADV" "Hoje_ADV em_PREP dia_N" :mm :mwe :misc "MWE=Hoje_em_dia|MWEPOS=ADV")
(-> "em_* aberto_*" "em_PREP aberto_ADJ" :mm :mwe :misc "MWE=em_aberto|MWEPOS=ADV")

;;MWEs equivalentes a CONJs
(-> "Mas_KC tanto_KC" "Mas_KC tanto_ADV" :mm :mwe :misc "MWE=Mas_tanto|MWEPOS=CONJ")    
(-> "no_KC entanto_KC" "no_PREP entanto_ADV" :mm :mwe :misc "MWE=no_entanto|MWEPOS=CONJ") 
(-> "No_KC entanto_KC" "No_PREP entanto_ADV" :mm :mwe :misc "MWE=No_entanto|MWEPOS=CONJ")  
(-> "bem_KC como_KC" "bem_ADV como_PREP" :mm :mwe :misc "MWE=bem_como|MWEPOS=CONJ")  
(-> "não_KC só_KC" "não_ADV só_ADV" :mm :mwe :misc "MWE=não_só|MWEPOS=CONJ")  
(-> "como_KC também_KC" "como_PREP também_ADV" :mm :mwe :misc "MWE=como_também|MWEPOS=CONJ")  
(-> "assim_KC como_KC" "assim_ADV como_PREP" :mm :mwe :misc "MWE=assim_como|MWEPOS=CONJ")    
(-> "Assim_KC como_KC" "Assim_ADV como_PREP" :mm :mwe :misc "MWE=Assim_como|MWEPOS=CONJ")   
(-> "no_KC entando_KC" "no_PREP entando_ADV" :typo :mm :mwe :misc "MWE=no_entanto|MWEPOS=CONJ")
(-> "a_KC não_KC ser_KC" "a_KC não_ADV ser_V" :mm :mwe :misc "MWE=a_não_ser|MWEPOS=CONJ")  
(-> "A_KC não_KC ser_KC" "A_KC não_ADV ser_V" :mm :mwe :misc "MWE=A_nâo_ser|MWEPOS=CONJ")  
(-> "Não_KC só_KC" "Não_ADV só_ADV" :mm :mwe :misc "MWE=Não_só|MWEPOS=CONJ") 
(-> "Mesmo_KC assim_KC" "Mesmo_KC assim_ADV" :mm :mwe :misc "MWE=Mesmo_assim|MWEPOS=CONJ")
(-> "Só_KC que_KC" "Só_ADV que_KC" :mm :mwe :misc "MWE=Só_que|MWEPOS=CONJ")
(-> "Ou_KC seja_KC" "Ou_KC seja_V" :mm :mwe :misc "MWE=Ou_seja|MWEPOS=CONJ")
(-> "Ainda_KC assim_KC" "Ainda_ADV assim_ADV" :mm :mwe :misc "MWE=Ainda_assim|MWEPOS=CONJ")
(-> "apesar_KC disso_KC" "apesar_KC disso_PROSUB" :mm :mwe :misc "MWE=apesar_disso|MWEPOS=CONJ")
(-> "além_KC de_KC" "além_ADV de_PREP" :mm :mwe :misc "MWE=além_de|MWEPOS=CONJ")
(-> "ainda_KC assim_KC" "ainda_ADV assim_ADV" :mm :mwe :misc "MWE=ainda_assim|MWEPOS=CONJ") 
(-> "quer_KC dizer_KC" "quer_V dizer_V" :mm :mwe :misc "MWE=quer_dizer|MWEPOS=CONJ")

;; regra PDEN 1
(-> "isto_PDEN é_PDEN" "isto_PROSUB é_V" :mm :mwe :misc "MWE=isto_é|MWEPOS=ADV")
(-> "Isto_PDEN é_PDEN" "Isto_PROSUB é_V" :mm :mwe :misc "MWE=Isto_é|MWEPOS=ADV")
(-> "ou_PDEN seja_PDEN" "ou_KC seja_V" :mm :mwe :misc "MWE=ou_seja|MWEPOS=ADV")
(-> "Ou_PDEN seja_PDEN" "Ou_KC seja_V" :mm :mwe :misc "MWE=Ou_seja|MWEPOS=ADV")
(-> "por_PDEN exemplo_PDEN" "por_PREP exemplo_N" :mm :mwe :misc "MWE=por_exemplo|MWEPOS=ADV")
(-> "Por_PDEN exemplo_PDEN" "Por_PREP exemplo_N" :mm :mwe :misc "MWE=Por_exemplo|MWEPOS=ADV")
(-> "p._PDEN ex._PDEN" "p._PREP ex._N" :mm :mwe :misc "MWE=p. ex.|MWEPOS=ADV")
(-> "quer_PDEN dizer_PDEN" "quer_V dizer_V" :mm :mwe :misc "MWE=quer_dizer|MWEPOS=ADV")
(-> "Quer_PDEN dizer_PDEN" "Quer_V dizer_V" :mm :mwe :misc "MWE=Quer_dizer|MWEPOS=ADV")
(-> "Pois_PDEN é_PDEN" "Pois_KC é_V" :mm :mwe :misc "MWE=Pois_é|MWEPOS=ADV")
(-> "por_PDEN aí_PDEN vai_PDEN" "por_PREP aí_PDEN vai_V" :typo)
(-> "assim_PDEN em_PDEN diante_PDEN" "assim_ADV em_PREP diante_PREP" :mm :mwe :misc "MWE=assim_em_diante|MWEPOS=ADV")
(-> "Assim_PDEN em_PDEN diante_PDEN" "Assim_ADV em_PREP diante_PREP" :mm :mwe :misc "MWE=Assim_em_diante|MWEPOS=ADV")    
(-> "assim_PDEN por_PDEN diante_PDEN" "assim_ADV por_PREP diante_PREP" :mm :mwe :misc "MWE=assim_por_diante|MWEPOS=ADV")
(-> "Assim_PDEN por_PDEN diante_PDEN" "Assim_ADV por_PREP diante_PREP" :mm :mwe :misc "MWE=Assim_por_diante|MWEPOS=ADV")
(-> "de_PDEN aqui_PDEN em_PDEN diante_PDEN" "de_PREP aqui_ADV em_PREP diante_PREP"
    :mm :mwe :misc "MWE=de_aqui_em_diante|MWEPOS=ADV")
(-> "de_PDEN agora_PDEN em_PDEN diante_PDEN" "de_PREP agora_ADV em_PREP diante_PREP"
    :mm :mwe :misc "MWE=de_agora_em_diante|MWEPOS=ADV")
(-> "por_PDEN diante_PDEN" "por_PREP diante_PREP" :mm :mwe :misc "MWE=por_diante|MWEPOS=ADV")
(-> "Por_PDEN diente_PDEN" "Por_PREP diante_PREP" :mm :mwe :misc "MWE=Por_diante|MWEPOS=ADV")
(-> "em_PDEN diante_PDEN" "em_PREP diante_PREP" :mm :mwe :misc "MWE=em_diante|MWEPOS=ADV")  
(-> "Em_PDEN diente_PDEN" "Em_PREP diante_PREP" :mm :mwe :misc "MWE=Em_diante|MWEPOS=ADV")
(-> "afinal_PDEN de_PDEN contas_PDEN" "Afinal_ADV de_PREP contas_N" :mm :mwe :misc "MWE=afinal_de_contas|MWEPOS=ADV")
(-> "ao_PDEN menos_PDEN" "ao_PREP menos_ADV" :mm :mwe :misc "MWE=ao_menos|MWEPOS=ADV")
(-> "Ao_PDEN menos_PDEN" "Ao_PREP menos_ADV" :mm :mwe :misc "MWE=Ao_menos|MWEPOS=ADV")
(-> "pelo_PDEN menos_PDEN" "pelo_PREP menos_ADV" :mm :mwe :misc "MWE=pelo_menos|MWEPOS=ADV")
(-> "ñpelo_N menos_PDEN" "pelo_PREP menos_ADV" :cr)
(-> "por_PDEN fim_PDEN" "por_PREP fim_N" :mm :mwe :misc "MWE=por_fim|MWEPOS=ADV")
(-> "pois_PDEN bem_PDEN" "pois_PREP bem_ADV" :mm :mwe :misc "MWE=pois_bem|MWEPOS=ADV")
(-> "Pois_PDEN bem_PDEN" "Pois_PREP bem_ADV" :mm :mwe :misc "MWE=Pois_bem|MWEPOS=ADV")

;; regra PDEN 2
(-> "ou_PDEN então_PDEN" "ou_KC então_ADV" :mm)
(-> "Ou_PDEN então_PDEN" "Ou_KC então_ADV" :mm)
(-> "ou_PDEN melhor_PDEN" "ou_KC melhor_ADV" :mm)
(-> "Ou_PDEN melhor_PDEN" "Ou_KC melhor_ADV" :mm)
(-> "quando_PDEN muito_PDEN" "quando_ADV muito_ADV" :dd)
(-> "que_PDEN instalaram_V" "que_KS instalaram_V" :cr)
(-> "por_PREP si_PROPESS mesmas_PDEN" "por_PREP si_PROPESS mesmas_PROADJ" :cr)
(-> "Olh*_V só_PDEN" "Olh*_V só_ADV" :dd)
(-> "olh*_V só_PDEN" "Olh*_V só_ADV" :dd)
(-> "Escut*_V só_PDEN" "Escut*_V só_ADV" :dd)
(-> "escut*_V só_PDEN" "escut*_V só_ADV" :dd)
(-> "Vej*_V só_PDEN" "Vej*_V só_ADV" :dd)
(-> "vej*_V só_PDEN" "vej*_V só_ADV" :dd)
(-> "é_PDEN que_PDEN" "é_V que_ADV" :dd)

;; regra PDEN 3
(-> "então_PDEN" "então_ADV" :dd)
(-> "Então_PDEN" "Então_ADV" :dd)
(-> "também_PDEN" "também_ADV" :dd)
(-> "Também_PDEN" "Também_ADV" :dd)
(-> "tambem_PDEN" "também_ADV" :cr)
(-> "idem_PDEN" "idem_ADV" :dd)
(-> "Idem_PDEN" "Idem_ADV" :dd)
(-> "talvez_PDEN" "talvez_ADV" :dd)
(-> "Talvez_PDEN" "Talvez_ADV" :dd)
(-> "apenas_PDEN" "apenas_ADV" :dd)
(-> "Apenas_PDEN" "Apenas_ADV" :dd)
(-> "ainda_PDEN" "ainda_ADV" :dd)
(-> "Ainda_PDEN" "Ainda_ADV" :dd)
(-> "mesmo_PDEN" "mesmo_ADV" :dd)
(-> "Mesmo_PDEN" "Mesmo_ADV" :dd)
(-> "só_PDEN" "só_ADV" :dd)
(-> "Só_PDEN" "Só_ADV" :dd)
(-> "já_PDEN" "já_ADV" :dd)
(-> "Já_PDEN" "Já_ADV" :dd)
(-> "aí_PDEN" "aí_ADV" :dd)
(-> "Aí_PDEN" "Aí_ADV" :dd)
(-> "nem_PDEN" "nem_ADV" :dd)
(-> "Nem_PDEN" "Nem_ADV" :dd)
(-> "daí_PDEN" "daí_ADV" :dd)
(-> "Daí_PDEN" "Daí_ADV" :dd)
(-> "eis_PDEN" "eis_ADV" :dd)
(-> "Eis_PDEN" "Eis_ADV" :dd)
(-> "sequer_PDEN" "sequer_ADV" :dd)
(-> "Sequer_PDEN" "Sequer_ADV" :dd)
(-> "assim_PDEN" "assim_ADV" :dd)
(-> "Assim_PDEN" "Assim_ADV" :dd)
(-> "somente_PDEN" "somente_ADV" :dd)
(-> "Somente_PDEN" "Somente_ADV" :dd)
(-> "sobretudo_PDEN" "sobretudo_ADV" :dd)
(-> "inclusive_PDEN" "inclusive_ADV" :dd)
(-> "Inclusive_PDEN" "Inclusive_ADV" :dd)
(-> "iclusive_PDEN" "iclusive_ADV" :typo)
(-> "menos_PDEN" "menos_ADV" :dd)
(-> "agora_PDEN" "agora_ADV" :dd)
(-> "sóó_PDEN" "sóó_PDEN" :typo)
(-> "não_PDEN" "não_ADV" :cr)
(-> "Não_PDEN" "Não_ADV" :cr)
(-> "senão_PDEN" "senão_ADV" :dd)
(-> "Senão_PDEN" "Senão_ADV" :dd)
(-> "tão_PDEN" "tão_ADV" :mm)
(-> "decerto_PDEN" "decerto_ADV" :dd)
(-> "fora_PDEN" "fora_ADV" :dd)
(-> "logo_PDEN" "logo_ADV" :dd)
(-> "aliás_PDEN" "aliás_ADV" :dd)
(-> "Aliás_PDEN" "Aliás_ADV" :dd)
(-> "agora_PDEN ,_," "agora_ADV ,_," :mm)
(-> "Agora_PDEN ,_," "Agora_ADV ,_," :mm)
(-> "afinal_PDEN" "afinal_ADV" :dd)
(-> "Afinal_PDEN" "Afinal_ADV" :dd)
(-> "enfim_PDEN" "enfim_ADV" :dd)
(-> "ademais_PDEN" "ademais_ADV" :dd)
(-> "melhor_PDEN" "melhor_ADV" :dd)
(-> "bem_PDEN" "bem_ADV" :mm)
(-> "Bem_PDEN" "Bem_ADV" :mm)
(-> "bom_PDEN" "bom_ADV" :mm)
(-> "Bom_PDEN" "Bom_ADV" :mm)
(-> "Logo_PDEN quem_PROSUB" "Logo_ADV quem_PROSUB" :dd)
(-> "cadê_PDEN" "cadê_ADV" :dd)
(-> "Cadê_PDEN" "Cadê_ADV" :dd)
(-> "tal_PDEN" "tal_ADV" :dd)

;; regra PDEN 4
(-> "etc_PDEN" "etc_X" :mm)
(-> "etc._PDEN" "etc._X" :mm)
(-> "etcétera_PDEN" "etcétera_X" :mm)
(-> "sic_PDEN" "sic_X" :dd)

;; regra PDEN 5
(-> "foi_PDEN" "foi_V" :dd)
(-> "Foi_PDEN" "Foi_V" :dd)
(-> "era_PDEN" "era_V" :dd) 
(-> "São_PDEN" "são_V" :cr)
(-> "é_PDEN" "é_V" :mm) 
(-> "É_PDEN" "É_V" :mm)
(-> "serão_PDEN" "serão_V" :cr) 

;; regra PDEN 6
(-> "salvo_PDEN" "salvo_PREP" :dd) 
(-> "de_PDEN" "de_PREP" :cr)
(-> "até_PDEN" "até_PREP" :dd)
(-> "Até_PDEN" "Até_PREP" :dd)

;; regra PDEN 7
(-> "Me_PROPESS Too_PDEN" "Me_NPROP Too_NPROP" :cr)
(-> "I._PDEN é_PDEN ,_," "I._X é_V ,_," :cr :typo)
(-> ",_PDEN ,_PDEN" ",_," :cr)

;; regra PDEN 8
(-> "Ciao_PDEN" "Ciao_INTJ" :mm)
(-> "Obrigad*_PDEN" "Obrigad*_INTJ" :mm)
(-> "que_PDEN" "que_KC" :dd)
(-> "daqui_PDEN" "daqui_PREP" :mm)
(-> "ó_PDEN" "ó_PART" :mm)
(-> "e_PDEN" "e_KC" :mm)
(-> "mesmos_PDEN" "mesmos_PROADJ" :mm)
(-> "marré_PDEN marré_PDEN" "marré_ADJ marré_ADJ" :dd)

;; correcoes gerais
(-> "à_PREP" "a_PREP a_ART" :cr)
(-> "de_N" "de_PREP" :dd)
(-> "da_N" "de_PREP a_ART" :dd)
(-> "do_N" "de_PREP o_ART" :dd)
(-> "d'_N" "d'_PREP" :dd)
(-> "quilos_N per_N capta/ano_N" "quilos_N per_PREP capta/ano_N" :dd)
(-> "brasileiros_N sem_N terra_N" "brasileiros_N sem_PREP terra_N" :dd)
(-> "mosca_N de_N o_N chifre_N" "mosca_N de_PREP o_ART chifre_N" :dd)
(-> "lúpus_N eritematoso_N sistêmico_N" "lúpus_N eritematoso_ADJ sistêmico_ADJ" :dd)
(-> "suspensão_N condicional_N da_N pena_N" "suspensão_N condicional_ADJ de_PREP a_ART pena_N" :mm)
(-> "Minas_N e_N Energia_N" "Minas_N e_KC Energia_N" :cr)
(-> "lei_N n_N º_N" "lei_N n_N º_X" :cr :typo)
(-> "segunda_N feira_N" "segunda_N feira_N" :typo)
(-> "Meio_N a_N meio_N" "Meio_N a_PREP meio_N" :cr)
(-> "Milwaukee_N Bucks_N" "Milwaukee_NPROP Bucks_NPROP" :cr)
(-> "Portland_N ,_, La_N Clippers_N" "Portland_NPROP ,_, La_NPROP Clippers_NPROP" :cr)
(-> "Phoenix_N Suns_N Sacramento_N Kings_N" "Phoenix_NPROP Suns_NPROP Sacramento_NPROP Kings_NPROP" :cr)
(-> "Atlanta_N" "Atlanta_NPROP" :cr)
(-> "Atalanta[_N x_N Udinese(23)_N ;_; Foggia(27)_N x_N Piacenza(27)_N ;_; Genoa(27)_N x_N Lazio(37)_N ;_; Lecce(11,_N aritimeticamente_N em_N a_N Série_N B)_N x_N Torino(30)_N ;_; Reggiana(22,_N um_N jogo_N a_N menos)_N x_N Napoli(30)_N ;_; Roma(26)_N x_N Cagliari(27)_N" "Atalanta_NPROP x_X Udinese_NPROP (_( 23_NUM )_) ;_; Foggia_NPROP (_( 27_NUM )_) x_X  Piacenza_NPROP (_( 27_NUM )_) ;_; Genoa_NPROP (_( 27_NUM  )_) x_X  Lazio_NPROP (_( 37_NUM )_) ;_; Lecce_NPROP (_( 11_NUM ,_, aritimeticamente_ADV em_PREP a_ART Série_N B_N )_) x_X Torino_NPROP (_( 30_NUM )_) ;_; Reggiana_NPROP (_( 22_NUM ,_, um_NUM jogo_N a_PROADJ menos_PROADJ )_) x_X  Napoli_NPROP (_( 30_NUM )_) ;_; Roma_NPROP (_( 26_NUM )_) x_X  Cagliari_NPROP (_( 27_NUM )_)" :cr :dd)
(-> "Deus_N nos_N acuda_N" "Deus_NPROP nos_PROPESS acuda_V" :dd)
(-> "Peso_N PESADO_N Dirigentes_N" "Peso_N PESADO_ADJ Dirigentes_N" :cr :dd)
(-> "Que_N Deus_N nos_N ajude_N" "Que_KS Deus_NPROP nos_PROPESS ajude_V" :mm)
(-> "seleção_N todo_N mundo_N pára_V" "seleção_N todo_PROADJ mundo_N pára_V" :cr)
(-> "Que_N Deus_N Nos_N Ajude_N" "Que_KS Deus_NPROP Nos_PROPESS Ajude_V" :dd)
(-> "boca_N Coordenador_N rebate_N" "boca_N Coordenador_N rebate_V" :cr)
(-> "Piloto_N fez_N" "Piloto_N fez_V" :cr)
(-> "Jogue_N Limpo_N no_N Esporte_N e_N na_N Vida_N" "Jogue_V Limpo_ADV em_PREP o_ART Esporte_N e_KC em_PREP a_ART Vida_N" :mm)
(-> "jogo_N Milan_N" "jogo_N Milan_NPROP" :cr)
(-> "Salzburg_N 0_N" "Salzburg_NPROP 0_NUM" :cr)
(-> "Hp_N DeskJet_N" "Hp_NPROP DeskJet_NPROP" :cr)
(-> "engenharia/sistemas_N digitais_N sistemas_N" "engenharia/sistemas_N digitais_ADJ sistemas_N" :mm)
(-> "AcerPower_N" "AcerPower_NPROP" :cr)
(-> "Z-Star_N" "Z-Star_NPROP" :cr)
(-> "Z-Note_N" "Z-Note_NPROP" :cr)
(-> "a_PREP Hp_N" "a_PREP Hp_NPROP" :cr)
(-> "on_N line_N" "online_ADJ" :dd)
(-> "linha_N Hp_N" "linha_N Hp_NPROP" :cr)
(-> "unicamp_N" "unicamp_NPROP" :dd)
(-> "vice_N e_N versa_N" "vice_N e_KC versa_N" :dd)
(-> "óculos_N 3_N D_N" "óculos_N 3_N D_N" :typo)
(-> "rapaz_N ñtricolor_N declaradoñ_N" "rapaz_N tricolor_ADJ declarado_V" :cr)
(-> "Ser_N ou_N não_N ser_N ..._N" "Ser_V ou_KC não_ADV ser_V ..._..." :dd)
(-> "Mas_N César_N é_N um_N homem_N onrado_N ..._N" "Mas_KC César_NPROP é_V um_ART homem_N onrado_ADJ ..._..." :mm)
(-> "beco_N sem_N saída_N" "beco_N sem_PREP saída_N" :mm)
(-> "Botafogo_N X_N Inter_N" "Botafogo_NPROP X_N Inter_NPROP" :cr)
(-> "combinação_N dsa_N tenor_N" "combinação_N dsa_PREP tenor_N" :cr :typo)
(-> "Hora_N extra_N Editoria_N" "Hora_N extra_ADJ Editoria_N" :cr)
(-> "café_N da_N manhã_N" "café_N de_PREP a_ART manhã_N" :mm)
(-> "Chegada_N a_PREP um_ART" "Chegada_ADJ a_PREP um_ART" :dd)
(-> "Cantor_N prova_N estar_V" "Cantor_N prova_V estar_V" :cr)
(-> "por_N" "por_PREP" :cr)
(-> "teatro_N da_N morte_N" "teatro_N de_PREP a_ART morte_N" :dd)
(-> "Haroldo_N Acton_N" "Haroldo_NPROP Acton_NPROP" :cr)
(-> "filmagens_N entraram_N V_N PREP_N final_ADJ" "filmagens_N entraram_V final_ADJ" :cr)
(-> "Caramelo_N Rigattoni_N Cocar_N" "Caramelo_NPROP Rigattoni_NPROP Cocar_NPROP" :cr)
(-> "ministro_N da_N Fazenda_N" "ministro_N de_PREP a_ART Fazenda_N" :dd)
(-> "ângulos_N ñdo_N tratamento_N" "ângulos_N de_PREP o_ART tratamento_N" :cr)
(-> "mico-leão_N da_N cara-dourada_N" "mico-leão_N de_PREP a_ART cara-dourada_N" :dd)
(-> "negócio_N da_N China_N" "negócio_N de_PREP a_ART China_N" :dd)
(-> "ataca_N anualmente_ADV" "ataca_V anualmente_ADV" :cr)
(-> "Pesquisa_N mostra_N" "Pesquisa_N mostra_V" :cr)
(-> "Fun_N by_N Phone_N" "Fun_NPROP by_NPROP Phone_NPROP" :cr)
(-> "Pega_N Ladrão_N" "Pega_V Ladrão_N" :cr :dd)
(-> "A_N inveja_N é_N uma_N merda_N" "A_ART inveja_N é_V uma_ART merda_N" :dd)
(-> "Os_ART moedeiros_N falsos_N" "Os_ART moedeiros_N falsos_ADJ" :cr)
(-> "papel_N higiênico_N" "papel_N higiênico_ADJ" :dd)
(-> "Filhos_N da_N puta_N" "Filhos_N de_PREP a_ART puta_N" :dd)
(-> "fala_V de_PREP arte_N e_N KCítica_N" "fala_V de_PREP arte_N e_KC KCítica_N" :cr :typo)
(-> "serviço_N secreto_N israelense_N" "serviço_N secreto_ADJ israelense_ADJ" :dd)
(-> "livre_N e_N justa_N" "livre_ADJ e_KC justa_ADJ" :dd)
(-> "grande_ADJ triunfo_N israelo_N palestino_N" "grande_ADJ triunfo_N israelo_ADJ palestino_ADJ" :cr)
(-> "Ficção_N científica_N" "Ficção_N científica_ADJ" :cr)
(-> "não_N pagamento_N" "não_ADV pagamento_N" :cr)
(-> "secretário_N nacional_N de_N turismo_N e_N Serviços_N" "secretário_N nacional_ADJ de_PREP turismo_N e_KC Serviços_N" :dd)
(-> "dia_N 23_N passado_N" "dia_N 23_N passado_ADJ" :cr)
(-> "dia_N a_N dia_N" "dia_N a_PREP dia_N" :dd)
(-> "fertilização_N in_N vitro_N" "fertilização_N in_PREP vitro_N" :cr :dd)
(-> "Discagem_N Direta_N à_N Distância_N" "Discagem_N Direta_ADJ a_PREP a_ART Distância_N" :cr :dd)
(-> "analisado_V 2ª_N feira_N feira_N" "analisado_V 2ª_N feira_N feira_N" :typo)
(-> "os_ART chamados_N shopping_N centers_N" "os_ART chamados_V shopping_N centers_N" :dd)
(-> "processadores_N Alpha_N AXP_N" "processadores_N Alpha_NPROP AXP_NPROP" :cr)
(-> "Centro_N Brasileiro_N de_N Filosofia_N para_N Crianças_N" "Centro_N Brasileiro_ADJ de_PREP Filosofia_N para_PREP Crianças_N" :dd)
(-> "x_N" "x_SYM" :cr :dd)
(-> "X_N" "X_SYM" :cr :dd)
(-> "cadeirinhas_N ño_PROSUB" "cadeirinhas_N o_ART" :cr)
(-> "mil_NUM ñque_PRO-KS-REL" "mil_NUM que_PRO-KS-REL" :cr)
(-> "juros_N ño_PROSUB" "juros_N o_ART" :cr)
(-> "rapaz_N ñtricolor_N declaradoñ_N" "rapaz_N ñtricolor_ADJ declarado_V" :cr :typo)
(-> "ñonde_V moram_V" "onde_ADV-KS-REL moram_V" :cr)
(-> "ñou_N melhor_ADJ ,_, olheirasñ_N" "ou_KC melhor_ADJ ,_, olheiras_N" :cr)
(-> "ñsua_ADJ colega_N" "sua_PROADJ colega_N" :cr)
(-> "ñalternadamenteñ_N por_PREP" "alternadamente_ADV por_PREP" :cr)
(-> "ñclaroñ_N a_PROADJ" "claro_N a_PROADJ" :cr)
(-> "ñsem_PREP música_N" "sem_PREP música_N" :cr)
(-> "ñnem_KC abundam_V" "nem_KC abundam_V" :cr)
(-> "ñenquanto_N quadriplica_V" "enquanto_KS quadriplica_V" :cr)
(-> "ñdistanteñ_N de_PREP" "distante_N de_PREP" :cr)
(-> "ñentre_V eles_PROPESS um_ART Di_NPROP Cavalcantiñ_NPROP" "entre_V eles_PROPESS um_ART Di_NPROP Cavalcanti_NPROP" :cr)
(-> "ñque_V enfrenta_V ventos_N contra_ADV em_PREP o_ART setor_N cofreñ_N" "que_V enfrenta_V ventos_N contra_ADV em_PREP o_ART setor_N cofre_N" :cr)
(-> "ñmas_N pra_PREP" "mas_N pra_PREP" :cr)
(-> "ñcom_N direção_N" "com_PREP direção_N" :cr)
(-> "ñpasmemñ_N nunca_ADV" "pasmem_V nunca_ADV" :cr)
(-> "ñespecialmente_ADV de_PREP" "especialmente_ADV de_PREP" :cr)
(-> "ñda_N geração_N" "de_PREP a_ART geração_N" :cr)
(-> "ñpor_N que_KS" "por_PREP que_KS" :cr)
(-> "ñdo_N tratamento_N" "de_PREP o_N tratamento_N" :cr)
(-> "Capote_," "Capote_NPROP" :cr)
(-> "Z-Note_NPOP" "Z-Note_NPROP" :cr)
(-> "NPROP,_," "" :cr)
(-> "-_-" "-_PUNCT" :cr)
(-> "((_((" "((_PUNCT" :cr)
(-> "))_))" "))_PUNCT" :cr)
(-> "`_`" "`_PUNCT" :cr)
(-> "$_$" "$_SYM" :cr)
(-> "\(260\,_NUM" "\(_PUNCT 260_NUM \,_PUNCT" :cr)
(-> "=_=" "=_SYM" :cr)

;; linguas estrangeiras
(-> "maître_N à_N penser_N" "maître_X à_X penser_X" :cr)
(-> "Encadernadoras_N first_N class_N" "Encadernadoras_N first_X class_X" :cr)
(-> "white_N anglo-saxon_N protestant_N" "white_X anglo-saxon_X protestant_X" :cr)
(-> "made_N in_N Brazil_N" "made_N in_N Brazil_X" :cr)
(-> "marca_N high_N class_N" "marca_N high_X class_X" :cr :dd)
(-> "mensagem_N SUBSCRIBE_N Mini-JIR_N" "mensagem_N SUBSCRIBE_X Mini-JIR_X" :cr :dd)
(-> "blue_N jets_N jets_N" "blue_X jets_X" :cr)
(-> "ne_N plus_N ultra_N" "ne_X plus_X ultra_X" :cr)
(-> "white_N man'_N s_N nigger_N" "white_X man's_X nigger_X" :cr)
(-> "death_N by_N water_N" "death_X by_X water_X" :cr)
(-> "The_N tarantula_N rattling_N" "The_X tarantula_X rattling_X" :cr)
(-> "I_N walk_N on_N fire_N" "I_X walk_X on_X fire_X" :cr)
(-> "minimal_N pairs_N pairs_N" "minimal_X pairs_X" :cr)
(-> "law_N and_N economics_N" "law_X and_X economics_X" :cr)
(-> "pay_N for_N performance_N" "pay_X for_X performance_X" :cr)
(-> "Prime_N rate_N" "Prime_X rate_X" :cr)
(-> "running_N back_N back_N" "running_X back_X" :cr)
(-> "Siempre_N com_N la_N surda_N" "Siempre_X com_X la_X surda_X" :cr)
(-> "Maradonariz_N go_N home_N" "Maradonariz_X go_X home_X" :cr)
(-> "Maradona_N Fails_N Drug_N Test_N" "Maradona_X Fails_X Drug_X Test_X" :cr)
(-> "Freud_NPROP traduziu_V l'_N âme_N humaine_N por_PREP menschlicher_N Geist_N" "Freud_NPROP traduziu_V l'_X âme_X humaine_X por_PREP menschlicher_X Geist_X" :cr)
(-> "psychologie_N nouvelle_N por_PREP neue_N Seele_N ,_, conditions_N mentales_N por_PREP Seelenzustand_N" "psychologie_X nouvelle_X por_PREP neue_X Seele_X ,_, conditions_X mentales_X por_PREP Seelenzustand_X" :cr)
(-> "l'_N organe_N psychique_N por_PREP Seelenorgan_N" "l'_X organe_X psychique_X por_PREP Seelenorgan_X" :cr)
(-> "encontramos_V Beziehung_N von_N Leiblichem_N un_N Seelischem_N para_PREP psycho-physical_N relation_N relation_N" "encontramos_V Beziehung_X von_X Leiblichem_X un_X Seelischem_X para_PREP psycho-physical_X relation_X" :cr)
(-> "Appareil_N d'_N âme_N ,_, como_PREP versão_N de_PREP Seelenapparat_N" "Appareil_X d'_X âme_X ,_, como_PREP versão_N de_PREP Seelenapparat_X" :cr)
(-> "manifester_N Trauminhalt_N é_VAUX vertido_V como_PREP contenu_N du_N rêve_N manifeste_N" "manifester_X Trauminhalt_X é_VAUX vertido_V como_PREP contenu_X du_X rêve_X manifeste_X" :cr)
(-> "katà_N phréna_ADJ kaì_N katà_N thymón_N" "katà_X phréna_X kaì_X katà_X thymón_X" :cr)
(-> "And_N The_N Oscar_N GOES_N" "And_X The_X Oscar_X GOES_X" :cr)
(-> "work_N in_N progress_N" "work_X in_X progress_X" :cr)
(-> "up_N to_N date_N" "up_X to_X date_X" :cr)
(-> "made_N in_N" "made_X in_X" :cr)
(-> "NOT_N FAIR_N" "NOT_X FAIR_X" :cr)
(-> "top_N beauty_N artist_N" "top_X beauty_X artist_X" :cr)
(-> "drags_N e_N dykes_N on_N bikes_N" "drags_N e_KC dykes_N on_X bikes_X" :cr)
(-> "up_N up_N away_N" "up_X up_X away_X" :cr)
(-> "Ooh_N aah_N Wonderbra_N" "Ooh_X aah_X Wonderbra_X" :cr)
(-> "Cup_N fever_N" "Cup_X fever_X" :cr)
(-> "carpal_N tunnel_N syndrome_N" "carpal_X tunnel_X syndrome_X" :cr)
(-> "me_N a_N non_N troppo_N" "me_X a_X non_X troppo_X" :cr)
(-> "personal_N digital_N assistant_N" "personal_X digital_X assistant_X" :cr)
(r-> "(\\w+)_ART PREP\\|\\+_ART" "\\1_PREP" :cr)
(-> "quorum\\|_N" "quorum_N" :cr)

(-> "até_PART" "até_PREP" :mm)
(-> "Até_PART" "Até_PREP" :mm)


;; OUTRAS REGRAS
(r-> "(\\w+)_ART (\\w+)_ADJ (\\w+)_([^N])" "\\1_ART \\2_N \\3_\\4")

;; para evitar que 1000_NUM seja matched com a regra abaixo,
;; temos que dizer que _N e' seguido de um ou mais espacos.
(r-> "(\\s+)([\\d\\,\\.\\º\\-\\/]+)_N(\\s+)" "\\1\\2_NUM\\3")

;; a regra acima nao funciona se _N for a ultima coisa na linha.
;; Esta regra abaixo serve pra isso:
(r-> "([\\d\\,\\.\\º\\-\\/]+)_N$" "\\1_NUM")

(r-> "(ADJ|PREP|ADV|VAUX|KC|ART|PROADJ|IN|N|NUM|PROPESS|PROSUB|NPROP|PU|KS|PRO-KS|PRO-KS-REL|ADV-KS|ADV-KS-REL|CUR|V|PCP|PDEN)_(SCONJ|DET|ADJ|PREP|ADV|VAUX|KC|ART|PROADJ|IN|N|NUM|PROPESS|PROSUB|NPROP|PU|KS|PRO-KS|PRO-KS-REL|ADV-KS|ADV-KS-REL|CUR|V|PCP|PDEN)" "" :cr)

(-> "%_NUM" "%_SYM" :mm)
(-> "%_N" "%_SYM" :mm)
(-> ":_:" ":_PUNCT" :mm)
(-> "!_!" "!_PUNCT" :mm)
(-> "?_?" "?_PUNCT" :mm)
(-> ";_;" ";_PUNCT" :mm)
(-> ",_," ",_PUNCT" :mm)
(-> "._." "._PUNCT" :mm)
(-> "..._..." "..._PUNCT" :mm)
(-> "(_(" "\(_PUNCT" :mm)
(-> ")_)" "\)_PUNCT" :mm)
(-> "[_[" "\[_PUNCT" :mm)
(-> "]_]" "\]_PUNCT" :mm)
(-> "{_{" "\{_PUNCT" :mm)
(-> "}_}" "\}_PUNCT" :mm)
(-> "\\\\_\\\\" "\\\\_PUNCT" :mm)
(-> "/_/" "\/_PUNCT" :mm)
(-> "<_<" "\<_PUNCT" :mm)
(-> ">_>" "\>_PUNCT" :mm)
(-> "\"\_\"" "\"_PUNCT" :mm)
(-> "\'\_\'" "\'_PUNCT" :mm)
(-> "*_PCP" "*_V" :dd)
(-> "*_PDEN" "*_ADV" :dd)
(-> "*_PREP" "*_ADP" :mm)
(-> "*_VAUX" "*_AUX" :mm)
(-> "*_KC" "*_CONJ" :mm)
(-> "*_ART" "*_DET" :mm)
(-> "*_PROADJ" "*_DET" :dd)
(-> "*_IN" "*_INTJ" :mm)
(-> "*_NPROP" "*_PROPN" :mm)
(-> "*_PROPESS" "*_PRON" :mm)
(-> "*_PROSUB" "*_PRON" :dd)
(-> "*_PRO-KS-REL" "*_SCONJ" :mm)
(-> "*_PRO-KS" "*_SCONJ" :mm)
(-> "*_ADV-KS-REL" "*_SCONJ" :mm)
(-> "*_ADV-KS" "*_SCONJ" :mm)
(-> "*_KS" "*_SCONJ" :mm)
(-> "*_CUR" "*_SYM" :mm)
(-> "*_V" "*_VERB" :mm)
(-> "*_N" "*_NOUN" :mm)
(-> "*_NOUNUM" "*_NUM" :mm)
(-> "*_DET PREP\\|\\+_DET" "*_ADP" :cr)
