;;correcoes ADJ para PCP
(-> "adequado_ADJ" "adequado_PCP" :cr)
(-> "intencionado_ADJ" "intencionado_PCP" :cr)
(-> "Adquirido_ADJ" "Adquirido_PCP" :cr)
(-> "esperado_ADJ" "esperado_PCP" :cr)
(-> "apavorado_ADJ" "apavorado_PCP" :cr)
(-> "pesado_ADJ" "pesado_PCP" :cr)
(-> "teleguiado_ADJ" "teleguiado_PCP" :cr)
(-> "privado_ADJ" "privado_PCP" :cr)
(-> "querido_ADJ" "querido_PCP" :cr)
(-> "dourado_ADJ" "dourado_PCP" :cr)
(-> "renomado_ADJ" "renomado_PCP" :cr)
(-> "colorido_ADJ" "colorido_PCP" :cr)
(-> "prateado_ADJ" "prateado_PCP" :cr)
(-> "comportado_ADJ" "comportado_PCP" :cr)
(-> "incluido_ADJ" "incluido_PCP" :cr)
(-> "letrado_ADJ" "letrado_PCP" :cr)
(-> "esclerosado_ADJ" "esclerosado_PCP" :cr)
(-> "lexotado_ADJ" "lexotado_PCP" :cr)
(-> "escolado_ADJ" "escolado_PCP" :cr)
(-> "apavorado_ADJ" "apavorado_PCP" :cr)
(-> "Alienado_ADJ" "Alienado_PCP" :cr)
(-> "roído_ADJ" "roído_PCP" :cr)
(-> "ferido_ADJ" "ferido_PCP" :cr)
(-> "passado_ADJ" "passado_PCP" :cr)
(-> "armado_ADJ" "armado_PCP" :cr)
(-> "falado_ADJ" "falado_PCP" :cr)
(-> "sincronizado_ADJ" "sincronizado_PCP" :cr)
(-> "computadorizado_ADJ" "computadorizado_PCP" :cr)
(-> "vermelho/amarelado_ADJ" "vermelho/amarelado_PCP" :cr) 
(-> "amarelado_ADJ" "amarelado_PCP" :cr)
(-> "azulado_ADJ" "azulado_PCP" :cr)
(-> "ensandecido_ADJ" "ensandecido_PCP" :cr)
(-> "associado_ADJ" "associado_PCP" :cr)
(-> "pesada_ADJ" "pesada_PCP" :cr) 
(-> "ensolarada_ADJ" "ensolarada_PCP" :cr) 
(-> "computadorizada_ADJ" "computadorizada_PCP" :cr) 
(-> "nascida_ADJ" "nascida_PCP" :cr) 
(-> "suada_ADJ" "suada_PCP" :cr) 
(-> "roída_ADJ" "roída_PCP" :cr) 
(-> "estereotipada_ADJ" "estereotipada_PCP" :cr) 
(-> "lascada_ADJ" "lascada_PCP" :cr) 
(-> "civilizada_ADJ" "civilizada_PCP" :cr) 
(-> "iluminada_ADJ" "iluminada_PCP" :cr) 
(-> "passada_ADJ" "passada_PCP" :cr) 
(-> "interditada_ADJ" "interditada_PCP" :cr) 
(-> "autogerida_ADJ" "autogerida_PCP" :cr) 
(-> "internacionalizada_ADJ" "internacionalizada_PCP" :cr) 
(-> "animados_ADJ" "animados_PCP" :cr) 
(-> "antecipados_ADJ" "antecipados_PCP" :cr) 
(-> "arrojados_ADJ" "arrojados_PCP" :cr) 
(-> "Associados_ADJ" "Associados_PCP" :cr) 
(-> "auxiliados_ADJ" "auxiliados_PCP" :cr) 
(-> "coloridos_ADJ" "coloridos_PCP" :cr) 
(-> "computadorizados_ADJ" "computadorizados_PCP" :cr) 
(-> "descomprometidos_ADJ" "descomprometidos_PCP" :cr) 
(-> "despreparados_ADJ" "despreparados_PCP" :cr) 
(-> "dourados_ADJ" "dourados_PCP" :cr) 
(-> "efeminados_ADJ" "efeminados_PCP" :cr) 
(-> "entendidos_ADJ" "entendidos_PCP" :cr) 
(-> "estereotipados_ADJ" "estereotipados_PCP" :cr) 
(-> "importados_ADJ" "importados_PCP" :cr) 
(-> "listados_ADJ" "listados_PCP" :cr) 
(-> "pesados_ADJ" "pesados_PCP" :cr) 
(-> "pirateados_ADJ" "pirateados_PCP" :cr) 
(-> "tratados_ADJ" "tratados_PCP" :cr) 
(-> "tutelados_ADJ" "tutelados_PCP" :cr) 
(-> "descoberto_ADJ" "descoberto_PCP" :cr)  
(-> "ocultos_ADJ" "ocultos_PCP" :cr)
(-> "sujeito_ADJ" "sujeito_PCP" :cr)
(-> "suposto_ADJ" "suposto_PCP" :cr) 
(-> "supostos_ADJ" "supostos_PCP" :cr) 
(-> "abandonadas_ADJ" "abandonadas_PCP" :cr) 
(-> "armadas_ADJ" "armadas_PCP" :cr)  
(-> "chacinadas_ADJ" "chacinadas_PCP" :cr) 
(-> "estereotipadas_ADJ" "estereotipadas_PCP" :cr) 
(-> "securitizadas_ADJ" "securitizadas_PCP" :cr) 
(-> "aberta_ADJ" "aberta_PCP" :cr) 
(-> "abertas_ADJ" "abertas_PCP" :cr) 
(-> "dita_ADJ" "dita_PCP" :cr) 
(-> "ditas_ADJ" "ditas_PCP" :cr) 
(-> "morta_ADJ" "morta_PCP" :cr) 
(-> "restritas_ADJ" "restritas_PCP" :cr) 
(-> "solta_ADJ" "solta_PCP" :cr) 
(-> "soltas_ADJ" "soltas_PCP" :cr) 
(-> "sujeita_ADJ" "sujeita_PCP" :cr) 
(-> "vista_ADJ" "vista_PCP" :cr)

;;PCPs que na verdade são Ns
(-> "ruído_PCP" "ruído_N" :cr)
(-> "namorada_PCP" "namorada_N" :cr)
(-> "deputado_PCP" "deputado_N" :cr)
(-> "bacalhoada_PCP" "bacalhoada_N" :cr)
(-> "chibatadas_PCP" "chibatadas_N" :cr)
(-> "desempregados_PCP" "desempregados_N" :cr)
(-> "antentados_PCP" "antentados_N" :cr typo)
(-> "surto_PCP" "surto_N" :cr)
(-> "agrado_PCP" "agrado_N" :cr)
(-> "a_ART retomada_PCP" "a_ART retomada_N" :cr)
(-> "*_ART goleada_PCP" "*_ART goleada_N" :cr)
(-> "mal_N entendido_PCP" "mal_N entendido_N" :cr)
(-> "mal_N entendidos_ADJ" "mal_N entendidos_N" :cr)

;;outras correcoes
(-> "Brando_ADJ" "Brando_NPROP" :cr)
(-> "foi_V o_ART quarto_N colocado_PCP" "foi_V o_ART quarto_ADJ colocado_N" :cr)
(-> "31º_ADJ colocado_PCP" "31º_ADJ colocado_N" :cr)
(-> "bem_PCP *_PCP" "bem_ADV *_ADJ" :cr)
(-> "mal_PCP *_PCP" "mal_ADV *_ADJ" :cr)
(-> "comunicado_PCP oficial_N" "comunicado_N oficial_ADJ" :cr)
(-> "soldados_PCP britânicos_N" "soldados_N britânicos_ADJ" :cr)
(-> "distante_ADJ e_KC caminhadas_PCP mais_ADV longínquas_ADJ" "distante_ADJ e_KC caminhadas_N mais_ADV longínquas_ADJ" :cr)
(-> "medida_PCP provisória_ADJ" "medida_N provisória_ADJ" :cr)
(-> "medida_NPROP provisória_NPROP" "medida_N provisória_ADJ" :cr)
(-> "a_ART maior_ADJ goleada_PCP" "a_ART maior_ADJ goleada_N" :cr)
(-> "consideram_V críticas_ADJ exageradas_PCP" "consideram_V críticas_N exageradas_PCP" :cr)
(-> "É_V preciso_ADJ cuidados_PCP antes_ADV de_PREP" "É_V preciso_ADJ cuidados_N antes_ADV de_PREP" :cr)
(-> "serviços_N bancários_ADJ informatizados_PCP" "serviços_N bancários_ADJ informatizados_ADJ" :cr)
(-> "o_ART grande_ADJ homenageado_PCP" "o_ART grande_ADJ homenageado_N" :cr)
(-> "o_ART surpreendente_ADJ verdadeiro_ADJ culpado_PCP" "o_ART surpreendente_ADJ verdadeiro_ADJ culpado_N" :cr)
(-> "visada_PCP niilista_N" "visada_N niilista_ADJ" :cr)
(-> "maior_ADJ aliada_PCP de_PREP a_ART" "maior_ADJ aliada_N de_PREP a_ART" :cr)
(-> "uma_ART inimiga_ADJ acirrada_PCP" "uma_ART inimiga_N acirrada_PCP"  :cr)
(-> "tradicional_ADJ aliada_PCP de_PREP os_ART sérvios_N"  "tradicional_ADJ aliada_N de_PREP os_ART sérvios_N" :cr)
(-> "três_NUM últimas_ADJ partidas_PCP" "três_NUM últimas_ADJ partidas_N" :cr)
(-> "rodízios_N VAUX_PCP com_PREP" "rodízios_N com_PREP" :cr)
(-> "curta_PREP ADJ_PREP tecido_N listrado_PCP" "curta_ADJ tecido_N listrado_ADJ" :cr)
(-> "vezes_N demasiado_PCP óbvia_ADJ" "vezes_N demasiado_ADV óbvia_ADJ" :cr)
(-> "e_KC rodopiante_N" "e_KC rodopiante_ADJ" :cr)
(-> "mercado_N auto-_N regulado_PCP e_KC" "mercado_N auto-regulado_PCP e_KC" :cr)
(-> "Presos_PCP são_VAUX" "Presos_N são_VAUX" :cr)
(-> "trágico_N emaranhado_PCP" "trágico_ADJ emaranhado_N" :cr)
(-> "Retirada_PCP de_PREP as_ART tropas_N" "Retirada_N de_PREP as_ART tropas_N" :cr)
(-> "quilômetros_N quadrados_PCP" "quilômetros_N quadrados_ADJ" :cr)
(-> "ser_V enviadas_N datilografadas_PCP" "ser_V enviadas_V datilografadas_PCP" :cr)
(-> "os_ART chamados_N \"\_\" desaparecidos_PCP" "os_ART chamados_V \"\_\" desaparecidos_N" :cr)
(-> "presente_ADJ medida_PCP provisória_ADJ" "presente_ADJ medida_N provisória_ADJ" :cr)
(-> "resultado_PCP de_PREP o_ART" "resultado_N de_PREP o_ART" :cr )
(-> "de_PREP a_ART largada_PCP" "de_PREP a_ART largada_N" :cr)
(-> "Resultado_PCP" "Resultado_N" :cr)
(-> "branquinhos_N e_KC aplicados_PCP" "branquinhos_ADJ e_KC aplicados_PCP" :cr)
(-> "após_PREP a_ART largada_PCP" "após_PREP a_ART largada_N" :cr)
(-> "obrigado_PCP \!\_\!" "obrigado_IN \!\_\!" :cr)
(-> "cobrou_V fechado_PCP" "cobrou_V fechado_ADV" :cr)
(-> "o_ART vacilante_ADJ e_KC o_ART derrotado_PCP" "o_ART vacilante_N e_KC o_ART derrotado_N" :cr)
(-> "os_ART concentrados_PCP" "os_ART concentrados_N" :cr )
(-> "o_ART envaido_PCP" "o_ART envaido_N" :cr :typo)
(-> "chuta_V cruzado_PCP" "chuta_V cruzado_ADV" :cr )
(-> "que_KS os_PROSUB importados_PCP" "que_KS os_PROSUB importados_N" :cr)
(-> "o_ART integrado_PCP de_PREP" "o_ART integrado_N de_PREP" :cr)
(-> "coletor_N de_PREP dados_V" "coletor_N de_PREP dados_N" :cr)
(-> "\(\_\( saída_PCP \)\_\)" "\(\_\( saída_N \)\_\)" :cr)
(-> "volumes_N de_PREP dados_V" "volumes_N de_PREP dados_N" :cr)
(-> "Para_PREP os_ART esquecidos_PCP" "Para_PREP os_ART esquecidos_ADJ" :cr)
(-> "encontrar_V a_ART \(\_\( o_ART \)\_\) parceira_N \(\_\( o_N \)\_\) sonhada_V \(\_\( o_PCP \)\_\) em_PREP" "encontrar_V a_ART \(\_\( o_ART \)\_\) parceira_N \(\_\( o_ART \)\_\) sonhada_PCP \(\_\( o_ART \)\_\) em_PREP" :cr )
(-> "os_ART eleitos_PCP de_PREP" "os_ART eleitos_N de_PREP" :cr)
(-> "É_V preciso_ADJ cuidados_PCP" "É_V preciso_V cuidados_N" :cr)
(-> "de_PREP dados_V" "de_PREP dados_N" :cr)
(-> "serifadas_PCP e_KC não_ADV serifadas_V" "serifadas_ADJ e_KC não_ADV serifadas_ADJ" :cr)
(-> "posto_PCP de_PREP gasolina_N" "posto_N de_PREP gasolina_N" :cr)
(-> "imaginação_N corre_V solta_PCP" "imaginação_N corre_V solta_ADV" :cr)
(-> "dados_PCP de_PREP a_ART" "dados_N de_PREP a_ART" :cr)
(-> "tal_PROSUB uma_ART renovada_PCP" "tal_PROSUB uma_ART renovada_N" :cr)
(-> "o_ART surpreendente_ADJ verdadeiro_ADJ culpado_PCP" "o_ART surpreendente_ADJ verdadeiro_ADJ culpado_N" :cr)
(-> "Comidas_PCP leves_N" "Comidas_N leves_ADJ" :cr)
(-> "inchado_PCP e_KC careca_N" "inchado_ADJ e_KC careca_ADJ" :cr)
(-> "Convidado_PCP de_PREP a_ART" "Convidado_N de_PREP a_ART" :cr)
(-> "outro_PROADJ confederado_PCP" "outro_PROADJ confederado_N" :cr)
(-> "O_ART confederado_PCP" "O_ART confederado_N" :cr)
(-> "resultado_PCP de_PREP a_ART" "resultado_N de_PREP a_ART" :cr)
(-> "houve_V retomada_PCP" "houve_V retomada_N" :cr)
(-> "faz_V sentido_PCP" "faz_V sentido_N" :cr)
(-> "empregado_PCP de_PREP Melado_NPROP" "empregado_N de_PREP Melado_NPROP" :cr )
(-> "fascinada_PCP e_KC horrorizada_V" "fascinada_PCP e_KC horrorizada_PCP" :cr)
(-> "venial_ADJ são_V pinceladas_PCP" "venial_ADJ são_V pinceladas_N" :cr)
(-> "visada_PCP européia_N" "visada_N européia_N" :cr)
(-> "alternada_PCP e_KC sucessivamente_ADV" "alternada_ADV e_KC sucessivamente_ADV" :cr)
(-> "caminhadas_PCP mais_ADV longínquas_ADJ" "caminhadas_N mais_ADV longínquas_ADJ" :cr)
(-> "Obrigada_PCP ,_," "Obrigada_IN ,_," :cr)
(-> "Cuidado_PCP com_PREP" "Cuidado_N com_PREP" :cr )
(-> "considerado_V um_ART protegido_PCP" "considerado_V um_ART protegido_N" :cr)
(-> "a_ART proposta_PCP" "a_ART proposta_N" :cr)
(-> "Rússia_NPROP uma_ART aliada_PCP" "Rússia_NPROP uma_ART aliada_N" :cr)
(-> "uma_ART inimiga_ADJ acirrada_PCP" "uma_ART inimiga_N acirrada_ADJ" :cr)
(-> "cinco_NUM antentados_PCP" "cinco_NUM atentados_N" :cr)
(-> "foram_V presos_N e_KC interrogados_PCP" "foram_V presos_PCP e_KC interrogados_PCP"  :cr)
(-> "Obrigado_PCP \!\_\!" "Obrigado_IN \!\_\!" :cr)
(-> "que_KS os_PROSUB importados_PCP" "que_KS os_PROSUB importados_N" :cr)
(-> "e_KC cruzados_PCP" "e_KC cruzados_N" :cr)
(-> "o_ART maior_ADJ prejudicado_PCP" "o_ART maior_ADJ prejudicado_N" :cr)
(-> "foi_PCP VAUX_PCP a_PREP" "foi_VAUX a_PREP" :cr)
(-> "O_ART candidado_PCP de_PREP o_ART PRONA_NPROP" "O_ART candidato_N de_PREP o_ART PRONA_NPROP" :cr)
(-> "Rio_NPROP é_V resultado_PCP de_PREP" "Rio_NPROP é_V resultado_N de_PREP" :cr)
(-> "por_PREP seus_PROADJ governados_PCP" "por_PREP seus_PROADJ governados_N" :cr)
(-> "bronzeamento_N é_V resultado_PCP de_PREP" "bronzeamento_N é_V resultado_N de_PREP" :cr)
(-> "os_ART chamados_N \"\_\" desaparecidos_PCP" "os_ART chamados_V \"\_\" desaparecidos_N" :cr)
(-> "e_KC desaparecidos_PCP políticos_N" "e_KC desaparecidos_N políticos_ADJ" :cr)
(-> "aliado_PCP político_N de_PREP" "aliado_N político_ADJ de_PREP" :cr)
(-> "mal_PCP colocado_V" "mal_ADV colocado_PCP" :cr)
(-> "previdência_N privada_PCP" "previdência_N privada_ADJ" :cr)
(-> "bancário_ADJ de_PREP os_ART envolvidos_PCP" "bancário_ADJ de_PREP os_ART envolvidos_N" :cr)
(-> "homeopatia_N de_PREP desinformados_PCP" "homeopatia_N de_PREP desinformados_N" :cr)
(-> "entre_PREP as_ART beneficiadas_PCP" "entre_PREP as_ART beneficiadas_N" :cr)
(-> "de_PREP os_ART feridos_PCP foi_V" "de_PREP os_ART feridos_N foi_V" :cr)
(-> "os_PROSUB similares_ADJ importados_PCP" "os_PROSUB similares_N importados_ADJ"  :cr)
(-> "resultado_PCP de_PREP fusão_N" "resultado_N de_PREP fusão_N" :cr)
(-> "entre_PREP os_ART pesquisados_PCP" "entre_PREP os_ART pesquisados_N" :cr)
(-> "O_ART primeiro_ADJ beneficiado_PCP" "O_ART primeiro_ADJ beneficiado_N" :cr)
(-> "assim_ADV ,_, ou_KC assado_PCP" "assim_ADV ,_, ou_KC assado_ADV" :cr)
(-> "grid_N de_PREP largada_PCP" "grid_N de_PREP largada_N" :cr)
(-> "afetado_PCP e_KC caipira_N" "afetado_ADJ e_KC caipira_ADJ" :cr)
(-> "prejudicar_V os_ART aquinhoados_PCP" "prejudicar_V os_ART aquinhoados_N" :cr)
(-> "Obrigado_PCP" "Obrigado_IN" :cr)
(-> "aliados_PCP de_PREP o_ART governo_N" "aliados_N de_PREP o_ART governo_N" :cr)
(-> "resultado_PCP de_PREP o_ART cruzamento_N" "resultado_N de_PREP o_ART cruzamento_N" :cr)
(-> "tiveram_V resultado_PCP médio_ADJ" "tiveram_V resultado_N médio_ADJ" :cr)
(-> "por_PREP escrito_PCP" "por_PREP escrito_N"  :cr)
(-> "Infectados_PCP chegam_V a_PREP" "Infectados_N chegam_V a_PREP" :cr)
(-> "estuprada_V viva_N ou_KC morta_PCP" "estuprada_V viva_ADJ ou_KC morta_ADJ" :cr)
(-> "um_ART quadriculado_PCP de_PREP" "um_ART quadriculado_N de_PREP" :cr)
(-> "Em_PREP esse_PROADJ sentido_PCP" "Em_PREP esse_PROADJ sentido_N" :cr)
(-> "uma_ART relembrada_PCP em_PREP" "uma_ART relembrada_N em_PREP" :cr)
(-> "muitos_PROSUB escritos_PCP para_PREP" "muitos_PROSUB escritos_N para_PREP" :cr)
(-> "tese_N de_PREP doutorado_PCP" "tese_N de_PREP doutorado_N" :cr)
(-> "deixados_V como_PREP legado_PCP" "deixados_V como_PREP legado_N" :cr)
(-> "o_ART envolvido_PCP é_V" "o_ART envolvido_N é_V" :cr)
(-> "era_V adequado_ADJ a_PREP o_ART caso_N" "era_V adequado_PCP a_PREP o_ART caso_N" :cr)
(-> "Alienado_ADJ ._. Desinformado_PCP" "Alienado_PCP ._. Desinformado_PCP" :cr)
(-> "pesado_PCP de_PREP a_ART faixa-título_N" "pesado_ADJ de_PREP a_ART faixa-título_N" :cr)
(-> "desacertos_N (_( gastos_PCP )_) a_ART inflação_N" "desacertos_N (_( gastos_N )_) a_ART inflação_N" :cr)
(-> "crianças_N abandonadas_ADJ brasileiras_ADJ" "crianças_N abandonadas_PCP brasileiras_ADJ" :cr)
(-> "Atrás_PROADJ" "Atrás_ADV" :cr)
(-> "só_PROADJ" "só_PDEN" :cr)

;;MWEs

;;correcoes feitas durante a etapa MWE
(-> "e_KC agora_KC" "e_KC agora_ADV" :cr)
(-> "mas_KC também_KC" "mas_KC também_ADV" :cr)
(-> "não_KC tanto_KC" "não_ADV tanto_ADV" :cr)
(-> "e_KC ora_KC" "e_KC ora_ADV" :cr)
(-> "pois_KC tanto_KC" "pois_KC tanto_ADV" :cr)
(-> "e_KC portanto_KC" "e_KC portanto_ADV" :cr)
(-> "quando_KC não_KC" "quando_ADV não_ADV" :cr)
(-> "e_KC mais_KC" "e_KC mais_ADV" :cr)
(-> "e_KC por_KC" "e_KC por_PREP" :cr)  
(-> "e_KC nem_KC" "e_KC nem_ADV" :cr)  
(-> "e_KC assim_KC" "e_KC assim_ADV" :cr)
(-> "linha_ADV a_ADV linha_ADV" "linha_N a_PREP linha_N" :cr)
(-> "e_KC e_KC" "e_KC e_KC" :typo)
(-> "um_ADV pouco_ADV mais_ADV" "um_ART pouco_ADV mais_ADV" :cr)
(-> "um_ADV pouquinho_ADV mais_ADV" "um_ART pouquinho_ADV mais_ADV" :cr)
(-> "ao_ADV mesmo_ADV tempo_ADV" "ao_PREP mesmo_PROADJ tempo_N" :cr)
(-> "um_ADV pouco_ADV" "um_ART pouco_ADV" :cr)
(-> "mais_ADV para_ADV cima_ADV" "mais_ADV para_PREP cima_ADV" :cr)
(-> "mais_ADV do_ADV que_ADV" "mais_ADV do_PREP que_KS" :cr)
(-> "por_ADV minha_ADV causa_ADV" "por_PREP minha_PROADJ causa_N" :cr)
(-> "o_ADV mais_ADV rapidamente_ADV" "o_ADV mais_ADV rapidamente_ADV" :cr)
(-> "um_ADV tiquinho_ADV mais_ADV" "um_ART tiquinho_ADV mais_ADV" :cr)
(-> "talvez_ADV um_ADV pouco_ADV" "talvez_ADV um_ART pouco_ADV" :cr)
(-> "mais_ADV uma_ADV vez_ADV" "mais_ADV uma_ART vez_N" :cr)
(-> "um_ADV pouco_ADV devagar_ADV" "um_ART pouco_ADV devagar_ADJ" :cr)
(-> "um_ADV pouco_ADV assim_ADV" "um_ART pouco_ADV assim_ADV" :cr)
(-> "Um_ADV pouco_ADV antes_ADV" "Um_ART pouco_ADV antes_ADV" :cr)
(-> "o_ADV mais_ADV possível_ADV" "o_ART mais_ADV possível_ADJ" :cr)
(-> "o_ADV mais_ADV rapidamente_ADV" "o_ART mais_ADV rapidamente_ADV" :cr)
(-> "lá_ADV de_ADV cima_ADV" "lá_ADV de_PREP cima_ADV" :cr)
(-> "de_ADV igual_ADV para_ADV igual_ADV" "de_PREP igual_ADJ para_PREP igual_ADJ" :cr)
(-> "só_ADV por_ADV só_ADV" "só_ADV por_PREP só_ADV" :cr)
(-> "bico-_N de-pena_IN" "bico-de-pena_N" :cr)

;;MWEs equivalentes a ADVs
(-> "de_ADV manhã_ADV" "de_PREP manhã_N"  :mwe :misc "MWE=de_manhã|MWEPOS=ADV")      
(-> "ainda_ADV por_ADV cima_ADV" "ainda_ADV por_PREP cima_ADV"  :mwe :misc "MWE=ainda_por_cima|MWEPOS=ADV")
(-> "o_ADV quanto_ADV antes_ADV" "o_ART quanto_PREP antes_ADV"  :mwe :misc "MWE=o_quanto_antes|MWEPOS=ADV")
(-> "por_ADV acaso_ADV" "por_PREP acaso_N"  :mwe :misc "MWE=por_acaso|MWEPOS=ADV") 
(-> "em_ADV frente_ADV" "em_PREP frente_N"  :mwe :misc "MWE=em_frente|MWEPOS=ADV") 
(-> "em_ADV vigor_ADV" "em_PREP vigor_N"  :mwe :misc "MWE=em_vigor|MWEPOS=ADV")
(-> "de_ADV uma_ADV vez_ADV" "de_PREP uma_ART vez_N"  :mwe :misc "MWE=de_uma_vez|MWEPOS=ADV")
(-> "em_ADV diante_ADV" "em_PREP diante_PREP"  :mwe :misc "MWE=em_diante|MWEPOS=ADV")   
(-> "ponta_ADV a_ADV ponta_ADV" "ponta_N a_PREP ponta_N"  :mwe :misc "MWE=ponta_a_ponta|MWEPOS=ADV")
(-> "mais_ADV ou_ADV menos_ADV" "mais_ADV ou_KC menos_ADV"  :mwe :misc "MWE=mais_ou_menos|MWEPOS=ADV") 
(-> "de_ADV cabo_ADV a_ADV rabo_ADV" "de_PREP cabo_N a_PREP rabo_N"  :mwe :misc "MWE=|MWEPOS=ADV") 
(-> "de_ADV ponta_ADV a_ADV ponta_ADV" "de_PREP ponta_N a_PREP ponta_N"  :mwe :misc "MWE=de_ponta_a_ponta|MWEPOS=ADV") 
(-> "rasteiro_ADV à_ADV esquerda_ADV" "rasteiro_ADJ a_PREP a_ART esquerda_N" :cr  :mwe :misc "MWE=rasteiro_à_esquerda|MWEPOS=ADV")
(-> "aí_ADV por_ADV diante_ADV" "aí_ADV por_PREP diante_ADV"  :mwe :misc "MWE=aí_por_diante|MWEPOS=ADV")
(-> "assim_ADV por_ADV diante_ADV" "assim_ADV por_PREP diante_ADV"  :mwe :misc "MWE=assim_por_diante|MWEPOS=ADV")
(-> "por_ADV diante_ADV" "por_PREP diante_PREP"  :mwe :misc "MWE=por_diante|MWEPOS=ADV")
(-> "Frente_ADV a_ADV frente_ADV" "Frente_N a_PREP frente_N"  :mwe :misc "MWE=Frente_a_frente|MWEPOS=ADV")  
(-> "à_ADV noite_ADV" "a_PREP a_ART noite_N" :cr  :mwe :misc "MWE=a_a_noite|MWEPOS=ADV")  
(-> "a_ADV a_ADV noite_ADV" "a_PREP a_ART noite_N"  :mwe :misc "MWE=a_a_noite|MWEPOS=ADV")
(-> "a_ADV a_ADV tarde_ADV" "a_PREP a_ART tarde_N"  :mwe :misc "MWE=a_a_tarde|MWEPOS=ADV")
(-> "Nem_ADV de_ADV longe_ADV" "Nem_ADV de_PREP longe_ADV"  :mwe :misc "MWE=Nem_de_longe|MWEPOS=ADV") 
(-> "ponto_ADV a_ADV ponto_ADV" "ponto_N a_PREP ponto_N"  :mwe :misc "MWE=ponto_a_ponto|MWEPOS=ADV")   
(-> "de_ADV trás_ADV" "de_PREP trás_ADV"  :mwe :misc "MWE=de_trás|MWEPOS=ADV")
(-> "para_ADV frente_ADV" "para_PREP frente_N"  :mwe :misc "MWE=para_frente|MWEPOS=ADV") 
(-> "de_ADV graça_ADV" "de_PREP graça_N"  :mwe :misc "MWE=de_graça|MWEPOS=ADV")
(-> "De_ADV vez_ADV em_ADV quando_ADV" "De_PREP vez_N em_PREP quando_KS"  :mwe :misc "MWE=De_vez_em_quando|MWEPOS=ADV")
(-> "de_ADV vez_ADV em_ADV quando_ADV" "de_PREP vez_N em_PREP quando_KS"  :mwe :misc "MWE=de_vez_em_quando|MWEPOS=ADV")
(-> "por_ADV sua_ADV vez_ADV" "por_PREP sua_PROADJ vez_N"  :mwe :misc "MWE=por_sua_vez|MWEPOS=ADV")   
(-> "a_ADV contragosto_ADV" "a_PREP contragosto_N"  :mwe :misc "MWE=a_contragosto|MWEPOS=ADV")
(-> "pra_ADV lá_ADV de_ADV" "pra_PREP lá_ADV de_PREP"  :mwe :misc "MWE=pra_lá_de|MWEPOS=ADV") 
(-> "em_ADV breve_ADV" "em_PREP breve_ADV"  :mwe :misc "MWE=em_breve|MWEPOS=ADV")   
(-> "De_ADV vez_ADV" "De_PREP vez_N"  :mwe :misc "MWE=De_vez|MWEPOS=ADV")  
(-> "Até_ADV Que_ADV Enfim_ADV" "Até_PREP Que_KC Enfim_ADV"  :mwe :misc "MWE=|Até_Que_EnfimMWEPOS=ADV")
(-> "de_ADV volta_ADV" "de_PREP volta_N"  :mwe :misc "MWE=de_volta|MWEPOS=ADV")   
(-> "lado_ADV a_ADV lado_ADV" "lado_N a_PREP lado_N"  :mwe :misc "MWE=lado_a_lado|MWEPOS=ADV")  
(-> "volta_ADV e_ADV meia_ADV" "volta_N e_KC meia_ADJ"  :mwe :misc "MWE=volta_e_meia|MWEPOS=ADV")  
(-> "em_ADV primeiro_ADV lugar_ADV" "em_PREP primeiro_ADJ lugar_N"  :mwe :misc "MWE=em_primeiro_lugar|MWEPOS=ADV")    
(-> "de_ADV modo_ADV algum_ADV" "de_PREP modo_N algum_PROADJ"  :mwe :misc "MWE=de_modo_algum|MWEPOS=ADV") 
(-> "pelo_ADV contrário_ADV" "pelo_PREP contrário_N"  :mwe :misc "MWE=pelo_contrário|MWEPOS=ADV")
(-> "de_ADV cima_ADV a_ADV baixo_ADV" "de_PREP cima_ADV a_PREP baixo_ADV"  :mwe :misc "MWE=de_cima_a_baixo|MWEPOS=ADV")    
(-> "Cara_ADV a_ADV cara_ADV" "Cara_N a_PREP cara_N"  :mwe :misc "MWE=Cara_a_cara|MWEPOS=ADV")   
(-> "um_ADV a_ADV um_ADV" "um_PROSUB a_PREP um_PROSUB"  :mwe :misc "MWE=um_a_um|MWEPOS=ADV")
(-> "hoje_ADV em_ADV dia_ADV" "hoje_ADV em_PREP dia_N"  :mwe :misc "MWE=hoje_em_dia|MWEPOS=ADV")
(-> "cada_ADV vez_ADV mais_ADV" "cada_PROADJ vez_N mais_ADV"  :mwe :misc "MWE=cada_vez_mais|MWEPOS=ADV")
(-> "de_ADV alto_ADV a_ADV baixo_ADV" "de_PREP alto_ADV a_PREP baixo_ADV"  :mwe :misc "MWE=de_alto_a_baixo|MWEPOS=ADV")
(-> "o_ADV quanto_ADV antes_ADV" "o_ART quanto_ADV antes_ADV"  :mwe :misc "MWE=o_quanto_antes|MWEPOS=ADV")
(-> "passo_ADV a_ADV passo_ADV" "passo_N a_PREP passo_N"  :mwe :misc "MWE=passo_a_passo|MWEPOS=ADV")
(-> "aqui_ADV e_ADV ali_ADV" "aqui_ADV e_KC ali_ADV"  :mwe :misc "MWE=aqui_e_ali|MWEPOS=ADV")
(-> "em_ADV particular_ADV" "em_PREP particular_N"  :mwe :misc "MWE=em_particular|MWEPOS=ADV")
(-> "quase_ADV tanto_ADV quanto_ADV" "quase_ADV tanto_ADV quanto_ADV"  :mwe :misc "MWE=quase_tanto_quanto|MWEPOS=ADV")
(-> "por_ADV completo_ADV" "por_PREP completo_N"  :mwe :misc "MWE=por_completo|MWEPOS=ADV")
(-> "em_ADV seguida_ADV" "em_PREP seguida_N"  :mwe :misc "MWE=em_seguida|MWEPOS=ADV")
(-> "pouco_ADV a_ADV pouco_ADV" "pouco_ADV a_PREP pouco_ADV"  :mwe :misc "MWE=pouco_a_pouco|MWEPOS=ADV")
(-> "dos_ADV pés_ADV à_ADV cabeça_ADV" "dos_PREP pés_N à_PREP cabeça_N"  :mwe :misc "MWE=dos_pés_a_cabeça|MWEPOS=ADV")
(-> "Às_ADV vezes_ADV" "Às_PREP vezes_N"  :mwe :misc "MWE=Às_vezes|MWEPOS=ADV")
(-> "de_ADV cima_ADV para_ADV baixo_ADV" "de_PREP cima_ADV para_PREP baixo_ADV"  :mwe :misc "MWE=de_cima_para_baixo|MWEPOS=ADV")
(-> "de_ADV baixo_ADV para_ADV cima_ADV" "de_PREP baixo_ADV para_PREP cima_ADV"  :mwe :misc "MWE=de_baixo_para_cima|MWEPOS=ADV")
(-> "por_ADV trás_ADV" "por_PREP trás_ADV"  :mwe :misc "MWE=por_trás|MWEPOS=ADV")
(-> "vez_ADV por_ADV outra_ADV" "vez_N por_PREP outra_ADJ"  :mwe :misc "MWE=vez_por_outra|MWEPOS=ADV")
(-> "ao_ADV pé_ADV da_ADV letra_ADV" "ao_PREP pé_N da_PREP letra_N"  :mwe :misc "MWE=ao_pé_da_letra|MWEPOS=ADV")
(-> "a_ADV céu_ADV aberto_ADV" "a_PREP céu_N aberto_PCP"  :mwe :misc "MWE=a_céu_aberto|MWEPOS=ADV")
(-> "ao_ADV ar_ADV livre_ADV" "ao_PREP ar_N livre_ADJ"  :mwe :misc "MWE=ao_ar_livre|MWEPOS=ADV")
(-> "de_ADV bom_ADV grado_ADV" "de_PREP bom_ADJ grado_N"  :mwe :misc "MWE=de_bom_grado|MWEPOS=ADV")
(-> "por_ADV aí_ADV afora_ADV" "por_PREP aí_ADV afora_ADV"  :mwe :misc "MWE=por_aí_afora|MWEPOS=ADV")
(-> "com_ADV bons_ADV olhos_ADV" "com_PREP bons_ADJ olhos_N"  :mwe :misc "MWE=com_bons_olhos|MWEPOS=ADV")
(-> "em_ADV geral_ADV" "em_PREP geral_ADJ"  :mwe :misc "MWE=em_geral|MWEPOS=ADV")
(-> "de_ADV fato_ADV" "de_PREP fato_N"  :mwe :misc "MWE=de_fato|MWEPOS=ADV")
(-> "Em_ADV primeiro_ADV lugar_ADV" "Em_PREP primeiro_ADJ lugar_N"  :mwe :misc "MWE=Em_primeiro_lugar|MWEPOS=ADV")
(-> "de_ADV novo_ADV" "de_PREP novo_ADJ"  :mwe :misc "MWE=de_novo|MWEPOS=ADV")
(-> "mais_ADV um_ADV pouco_ADV" "mais_ADV um_ART pouco_ADV"  :mwe :misc "MWE=mais_um_pouco|MWEPOS=ADV")
(-> "baixo_ADV para_ADV cima_ADV" "baixo_ADV para_PREP cima_ADV"  :mwe :misc "MWE=baixo_pra_cima|MWEPOS=ADV")
(-> "nem_ADV ao_ADV menos_ADV" "nem_KC ao_PREP menos_ADV"  :mwe :misc "MWE=nem_ao_menos|MWEPOS=ADV")
(-> "De_ADV quando_ADV em_ADV quando_ADV" "De_PREP quando_ADV em_PREP quando_ADV"  :mwe :misc "MWE=De_quando_em_quando|MWEPOS=ADV")
(-> "a_ADV olho_ADV nu_ADV" "a_PREP olho_N nu_ADJ"  :mwe :misc "MWE=a_olho_nu|MWEPOS=ADV")
(-> "de_ADV quando_ADV em_ADV quando_ADV" "de_PREP quando_ADV em_PREP quando_ADV"  :mwe :misc "MWE=de_quando_em_quando|MWEPOS=ADV")
(-> "Por_ADV outro_ADV lado_ADV" "Por_PREP outro_ADJ lado_N"  :mwe :misc "MWE=Por_outro_lado|MWEPOS=ADV")
(-> "sem_ADV mais_ADV nem_ADV menos_ADV" "sem_PREP mais_ADV nem_PREP menos_ADV"  :mwe :misc "MWE=sem_mais_nem_menos|MWEPOS=ADV")
(-> "Hoje_ADV em_ADV dia_ADV" "Hoje_ADV em_PREP dia_N"  :mwe :misc "MWE=Hoje_em_dia|MWEPOS=ADV")
(-> "em_* aberto_*" "em_PREP aberto_ADJ"  :mwe :misc "MWE=em_aberto|MWEPOS=ADV")

;;MWEs equivalentes a CONJs
(-> "Mas_KC tanto_KC" "Mas_KC tanto_ADV"  :mwe :misc "MWE=Mas_tanto|MWEPOS=CONJ")    
(-> "no_KC entanto_KC" "no_PREP entanto_ADV"  :mwe :misc "MWE=no_entanto|MWEPOS=CONJ") 
(-> "No_KC entanto_KC" "No_PREP entanto_ADV"  :mwe :misc "MWE=No_entanto|MWEPOS=CONJ")  
(-> "bem_KC como_KC" "bem_ADV como_PREP"  :mwe :misc "MWE=bem_como|MWEPOS=CONJ")  
(-> "não_KC só_KC" "não_ADV só_ADV"  :mwe :misc "MWE=não_só|MWEPOS=CONJ")  
(-> "como_KC também_KC" "como_PREP também_ADV"  :mwe :misc "MWE=como_também|MWEPOS=CONJ")  
(-> "assim_KC como_KC" "assim_ADV como_PREP"  :mwe :misc "MWE=assim_como|MWEPOS=CONJ")    
(-> "Assim_KC como_KC" "Assim_ADV como_PREP"  :mwe :misc "MWE=Assim_como|MWEPOS=CONJ")   
(-> "no_KC entando_KC" "no_PREP entando_ADV" :typo  :mwe :misc "MWE=no_entanto|MWEPOS=CONJ")
(-> "a_KC não_KC ser_KC" "a_KC não_ADV ser_V"  :mwe :misc "MWE=a_não_ser|MWEPOS=CONJ")  
(-> "A_KC não_KC ser_KC" "A_KC não_ADV ser_V"  :mwe :misc "MWE=A_nâo_ser|MWEPOS=CONJ")  
(-> "Não_KC só_KC" "Não_ADV só_ADV"  :mwe :misc "MWE=Não_só|MWEPOS=CONJ") 
(-> "Mesmo_KC assim_KC" "Mesmo_KC assim_ADV"  :mwe :misc "MWE=Mesmo_assim|MWEPOS=CONJ")
(-> "Só_KC que_KC" "Só_ADV que_KC"  :mwe :misc "MWE=Só_que|MWEPOS=CONJ")
(-> "Ou_KC seja_KC" "Ou_KC seja_V"  :mwe :misc "MWE=Ou_seja|MWEPOS=CONJ")
(-> "Ainda_KC assim_KC" "Ainda_ADV assim_ADV"  :mwe :misc "MWE=Ainda_assim|MWEPOS=CONJ")
(-> "apesar_KC disso_KC" "apesar_KC disso_PROSUB"  :mwe :misc "MWE=apesar_disso|MWEPOS=CONJ")
(-> "além_KC de_KC" "além_ADV de_PREP"  :mwe :misc "MWE=além_de|MWEPOS=CONJ")
(-> "ainda_KC assim_KC" "ainda_ADV assim_ADV"  :mwe :misc "MWE=ainda_assim|MWEPOS=CONJ") 
(-> "quer_KC dizer_KC" "quer_V dizer_V"  :mwe :misc "MWE=quer_dizer|MWEPOS=CONJ")

;; regra PDEN 1
(-> "isto_PDEN é_PDEN" "isto_PROSUB é_V"  :mwe :misc "MWE=isto_é|MWEPOS=ADV")
(-> "Isto_PDEN é_PDEN" "Isto_PROSUB é_V"  :mwe :misc "MWE=Isto_é|MWEPOS=ADV")
(-> "ou_PDEN seja_PDEN" "ou_KC seja_V"  :mwe :misc "MWE=ou_seja|MWEPOS=ADV")
(-> "Ou_PDEN seja_PDEN" "Ou_KC seja_V"  :mwe :misc "MWE=Ou_seja|MWEPOS=ADV")
(-> "por_PDEN exemplo_PDEN" "por_PREP exemplo_N"  :mwe :misc "MWE=por_exemplo|MWEPOS=ADV")
(-> "Por_PDEN exemplo_PDEN" "Por_PREP exemplo_N"  :mwe :misc "MWE=Por_exemplo|MWEPOS=ADV")
(-> "p._PDEN ex._PDEN" "p._PREP ex._N"  :mwe :misc "MWE=p. ex.|MWEPOS=ADV")
(-> "quer_PDEN dizer_PDEN" "quer_V dizer_V"  :mwe :misc "MWE=quer_dizer|MWEPOS=ADV")
(-> "Quer_PDEN dizer_PDEN" "Quer_V dizer_V"  :mwe :misc "MWE=Quer_dizer|MWEPOS=ADV")
(-> "Pois_PDEN é_PDEN" "Pois_KC é_V"  :mwe :misc "MWE=Pois_é|MWEPOS=ADV")
(-> "por_PDEN aí_PDEN vai_PDEN" "por_PREP aí_PDEN vai_V" :typo)
(-> "assim_PDEN em_PDEN diante_PDEN" "assim_ADV em_PREP diante_PREP"  :mwe :misc "MWE=assim_em_diante|MWEPOS=ADV")
(-> "Assim_PDEN em_PDEN diante_PDEN" "Assim_ADV em_PREP diante_PREP"  :mwe :misc "MWE=Assim_em_diante|MWEPOS=ADV")    
(-> "assim_PDEN por_PDEN diante_PDEN" "assim_ADV por_PREP diante_PREP"  :mwe :misc "MWE=assim_por_diante|MWEPOS=ADV")
(-> "Assim_PDEN por_PDEN diante_PDEN" "Assim_ADV por_PREP diante_PREP"  :mwe :misc "MWE=Assim_por_diante|MWEPOS=ADV")
(-> "de_PDEN aqui_PDEN em_PDEN diante_PDEN" "de_PREP aqui_ADV em_PREP diante_PREP"
     :mwe :misc "MWE=de_aqui_em_diante|MWEPOS=ADV")
(-> "de_PDEN agora_PDEN em_PDEN diante_PDEN" "de_PREP agora_ADV em_PREP diante_PREP"
     :mwe :misc "MWE=de_agora_em_diante|MWEPOS=ADV")
(-> "por_PDEN diante_PDEN" "por_PREP diante_PREP"  :mwe :misc "MWE=por_diante|MWEPOS=ADV")
(-> "Por_PDEN diente_PDEN" "Por_PREP diante_PREP"  :mwe :misc "MWE=Por_diante|MWEPOS=ADV")
(-> "em_PDEN diante_PDEN" "em_PREP diante_PREP"  :mwe :misc "MWE=em_diante|MWEPOS=ADV")  
(-> "Em_PDEN diente_PDEN" "Em_PREP diante_PREP"  :mwe :misc "MWE=Em_diante|MWEPOS=ADV")
(-> "afinal_PDEN de_PDEN contas_PDEN" "Afinal_ADV de_PREP contas_N"  :mwe :misc "MWE=afinal_de_contas|MWEPOS=ADV")
(-> "ao_PDEN menos_PDEN" "ao_PREP menos_ADV"  :mwe :misc "MWE=ao_menos|MWEPOS=ADV")
(-> "Ao_PDEN menos_PDEN" "Ao_PREP menos_ADV"  :mwe :misc "MWE=Ao_menos|MWEPOS=ADV")
(-> "pelo_PDEN menos_PDEN" "pelo_PREP menos_ADV"  :mwe :misc "MWE=pelo_menos|MWEPOS=ADV")
(-> "ñpelo_N menos_PDEN" "pelo_PREP menos_ADV" :cr)
(-> "por_PDEN fim_PDEN" "por_PREP fim_N"  :mwe :misc "MWE=por_fim|MWEPOS=ADV")
(-> "pois_PDEN bem_PDEN" "pois_PREP bem_ADV"  :mwe :misc "MWE=pois_bem|MWEPOS=ADV")
(-> "Pois_PDEN bem_PDEN" "Pois_PREP bem_ADV"  :mwe :misc "MWE=Pois_bem|MWEPOS=ADV")

;; regra PDEN 2
(-> "ou_PDEN então_PDEN" "ou_KC então_ADV" )
(-> "Ou_PDEN então_PDEN" "Ou_KC então_ADV" )
(-> "ou_PDEN melhor_PDEN" "ou_KC melhor_ADV" )
(-> "Ou_PDEN melhor_PDEN" "Ou_KC melhor_ADV" )
(-> "quando_PDEN muito_PDEN" "quando_ADV muito_ADV" )
(-> "que_PDEN instalaram_V" "que_KS instalaram_V" :cr)
(-> "por_PREP si_PROPESS mesmas_PDEN" "por_PREP si_PROPESS mesmas_PROADJ" :cr)
(-> "Olh*_V só_PDEN" "Olh*_V só_ADV" )
(-> "olh*_V só_PDEN" "Olh*_V só_ADV" )
(-> "Escut*_V só_PDEN" "Escut*_V só_ADV" )
(-> "escut*_V só_PDEN" "escut*_V só_ADV" )
(-> "Vej*_V só_PDEN" "Vej*_V só_ADV" )
(-> "vej*_V só_PDEN" "vej*_V só_ADV" )
(-> "é_PDEN que_PDEN" "é_V que_ADV" )

;; regra PDEN 3
(-> "então_PDEN" "então_ADV" )
(-> "Então_PDEN" "Então_ADV" )
(-> "também_PDEN" "também_ADV" )
(-> "Também_PDEN" "Também_ADV" )
(-> "tambem_PDEN" "também_ADV" :cr)
(-> "idem_PDEN" "idem_ADV" )
(-> "Idem_PDEN" "Idem_ADV" )
(-> "talvez_PDEN" "talvez_ADV" )
(-> "Talvez_PDEN" "Talvez_ADV" )
(-> "apenas_PDEN" "apenas_ADV" )
(-> "Apenas_PDEN" "Apenas_ADV" )
(-> "ainda_PDEN" "ainda_ADV" )
(-> "Ainda_PDEN" "Ainda_ADV" )
(-> "mesmo_PDEN" "mesmo_ADV" )
(-> "Mesmo_PDEN" "Mesmo_ADV" )
(-> "só_PDEN" "só_ADV" )
(-> "Só_PDEN" "Só_ADV" )
(-> "já_PDEN" "já_ADV" )
(-> "Já_PDEN" "Já_ADV" )
(-> "aí_PDEN" "aí_ADV" )
(-> "Aí_PDEN" "Aí_ADV" )
(-> "nem_PDEN" "nem_ADV" )
(-> "Nem_PDEN" "Nem_ADV" )
(-> "daí_PDEN" "daí_ADV" )
(-> "Daí_PDEN" "Daí_ADV" )
(-> "eis_PDEN" "eis_ADV" )
(-> "Eis_PDEN" "Eis_ADV" )
(-> "sequer_PDEN" "sequer_ADV" )
(-> "Sequer_PDEN" "Sequer_ADV" )
(-> "assim_PDEN" "assim_ADV" )
(-> "Assim_PDEN" "Assim_ADV" )
(-> "somente_PDEN" "somente_ADV" )
(-> "Somente_PDEN" "Somente_ADV" )
(-> "sobretudo_PDEN" "sobretudo_ADV" )
(-> "inclusive_PDEN" "inclusive_ADV" )
(-> "Inclusive_PDEN" "Inclusive_ADV" )
(-> "iclusive_PDEN" "iclusive_ADV" :typo)
(-> "menos_PDEN" "menos_ADV" )
(-> "agora_PDEN" "agora_ADV" )
(-> "sóó_PDEN" "sóó_PDEN" :typo)
(-> "não_PDEN" "não_ADV" :cr)
(-> "Não_PDEN" "Não_ADV" :cr)
(-> "senão_PDEN" "senão_ADV" )
(-> "Senão_PDEN" "Senão_ADV" )
(-> "tão_PDEN" "tão_ADV" )
(-> "decerto_PDEN" "decerto_ADV" )
(-> "fora_PDEN" "fora_ADV" )
(-> "logo_PDEN" "logo_ADV" )
(-> "aliás_PDEN" "aliás_ADV" )
(-> "Aliás_PDEN" "Aliás_ADV" )
(-> "agora_PDEN ,_," "agora_ADV ,_," )
(-> "Agora_PDEN ,_," "Agora_ADV ,_," )
(-> "afinal_PDEN" "afinal_ADV" )
(-> "Afinal_PDEN" "Afinal_ADV" )
(-> "enfim_PDEN" "enfim_ADV" )
(-> "ademais_PDEN" "ademais_ADV" )
(-> "melhor_PDEN" "melhor_ADV" )
(-> "bem_PDEN" "bem_ADV" )
(-> "Bem_PDEN" "Bem_ADV" )
(-> "bom_PDEN" "bom_ADV" )
(-> "Bom_PDEN" "Bom_ADV" )
(-> "Logo_PDEN quem_PROSUB" "Logo_ADV quem_PROSUB" )
(-> "cadê_PDEN" "cadê_ADV" )
(-> "Cadê_PDEN" "Cadê_ADV" )
(-> "tal_PDEN" "tal_ADV" )

;; regra PDEN 4
(-> "etc_PDEN" "etc_X" )
(-> "etc._PDEN" "etc._X" )
(-> "etcétera_PDEN" "etcétera_X" )
(-> "sic_PDEN" "sic_X" )

;; regra PDEN 5
(-> "foi_PDEN" "foi_V" )
(-> "Foi_PDEN" "Foi_V" )
(-> "era_PDEN" "era_V" ) 
(-> "São_PDEN" "são_V" :cr)
(-> "é_PDEN" "é_V" ) 
(-> "É_PDEN" "É_V" )
(-> "serão_PDEN" "serão_V" :cr) 

;; regra PDEN 6
(-> "salvo_PDEN" "salvo_PREP" ) 
(-> "de_PDEN" "de_PREP" :cr)
(-> "até_PDEN" "até_PREP" )
(-> "Até_PDEN" "Até_PREP" )

;; regra PDEN 7
(-> "Me_PROPESS Too_PDEN" "Me_NPROP Too_NPROP" :cr)
(-> "I._PDEN é_PDEN ,_," "I._X é_V ,_," :cr :typo)
(-> ",_PDEN ,_PDEN" ",_," :cr)

;; regra PDEN 8
(-> "Ciao_PDEN" "Ciao_INTJ" )
(-> "Obrigad*_PDEN" "Obrigad*_INTJ" )
(-> "que_PDEN" "que_KC" )
(-> "daqui_PDEN" "daqui_PREP" )
(-> "ó_PDEN" "ó_PART" )
(-> "e_PDEN" "e_KC" )
(-> "mesmos_PDEN" "mesmos_PROADJ" )
(-> "marré_PDEN marré_PDEN" "marré_ADJ marré_ADJ" )

;; adaptacoes de tokenizacao/filosofia
(-> "à_PREP" "a_PREP a_ART" :cr)
(-> "de_N" "de_PREP" )
(-> "da_N" "de_PREP a_ART" )
(-> "do_N" "de_PREP o_ART" )
(-> "d'_N" "d'_PREP" )
(-> "quilos_N per_N capta/ano_N" "quilos_N per_PREP capta/ano_N" )
(-> "brasileiros_N sem_N terra_N" "brasileiros_N sem_PREP terra_N" )
(-> "mosca_N de_N o_N chifre_N" "mosca_N de_PREP o_ART chifre_N" )
(-> "lúpus_N eritematoso_N sistêmico_N" "lúpus_N eritematoso_ADJ sistêmico_ADJ" )
(-> "suspensão_N condicional_N da_N pena_N" "suspensão_N condicional_ADJ de_PREP a_ART pena_N" )
(-> "Minas_N e_N Energia_N" "Minas_N e_KC Energia_N" :cr)
(-> "lei_N n_N º_N" "lei_N n_N º_X" :cr :typo)
(-> "segunda_N feira_N" "segunda_N feira_N" :typo)
(-> "Meio_N a_N meio_N" "Meio_N a_PREP meio_N" :cr)
(-> "Milwaukee_N Bucks_N" "Milwaukee_NPROP Bucks_NPROP" :cr)
(-> "Portland_N ,_, La_N Clippers_N" "Portland_NPROP ,_, La_NPROP Clippers_NPROP" :cr)
(-> "Phoenix_N Suns_N Sacramento_N Kings_N" "Phoenix_NPROP Suns_NPROP Sacramento_NPROP Kings_NPROP" :cr)
(-> "Atlanta_N" "Atlanta_NPROP" :cr)
(-> "Atalanta[_N x_N Udinese(23)_N ;_; Foggia(27)_N x_N Piacenza(27)_N ;_; Genoa(27)_N x_N Lazio(37)_N ;_; Lecce(11,_N aritimeticamente_N em_N a_N Série_N B)_N x_N Torino(30)_N ;_; Reggiana(22,_N um_N jogo_N a_N menos)_N x_N Napoli(30)_N ;_; Roma(26)_N x_N Cagliari(27)_N" "Atalanta_NPROP x_X Udinese_NPROP (_( 23_NUM )_) ;_; Foggia_NPROP (_( 27_NUM )_) x_X  Piacenza_NPROP (_( 27_NUM )_) ;_; Genoa_NPROP (_( 27_NUM  )_) x_X  Lazio_NPROP (_( 37_NUM )_) ;_; Lecce_NPROP (_( 11_NUM ,_, aritimeticamente_ADV em_PREP a_ART Série_N B_N )_) x_X Torino_NPROP (_( 30_NUM )_) ;_; Reggiana_NPROP (_( 22_NUM ,_, um_NUM jogo_N a_PROADJ menos_PROADJ )_) x_X  Napoli_NPROP (_( 30_NUM )_) ;_; Roma_NPROP (_( 26_NUM )_) x_X  Cagliari_NPROP (_( 27_NUM )_)" :cr )
(-> "Deus_N nos_N acuda_N" "Deus_NPROP nos_PROPESS acuda_V" )
(-> "Peso_N PESADO_N Dirigentes_N" "Peso_N PESADO_ADJ Dirigentes_N" :cr )
(-> "Que_N Deus_N nos_N ajude_N" "Que_KS Deus_NPROP nos_PROPESS ajude_V" )
(-> "seleção_N todo_N mundo_N pára_V" "seleção_N todo_PROADJ mundo_N pára_V" :cr)
(-> "Que_N Deus_N Nos_N Ajude_N" "Que_KS Deus_NPROP Nos_PROPESS Ajude_V" )
(-> "boca_N Coordenador_N rebate_N" "boca_N Coordenador_N rebate_V" :cr)
(-> "Piloto_N fez_N" "Piloto_N fez_V" :cr)
(-> "Jogue_N Limpo_N no_N Esporte_N e_N na_N Vida_N" "Jogue_V Limpo_ADV em_PREP o_ART Esporte_N e_KC em_PREP a_ART Vida_N" )
(-> "jogo_N Milan_N" "jogo_N Milan_NPROP" :cr)
(-> "Salzburg_N 0_N" "Salzburg_NPROP 0_NUM" :cr)
(-> "Hp_N DeskJet_N" "Hp_NPROP DeskJet_NPROP" :cr)
(-> "engenharia/sistemas_N digitais_N sistemas_N" "engenharia/sistemas_N digitais_ADJ sistemas_N" )
(-> "AcerPower_N" "AcerPower_NPROP" :cr)
(-> "Z-Star_N" "Z-Star_NPROP" :cr)
(-> "Z-Note_N" "Z-Note_NPROP" :cr)
(-> "a_PREP Hp_N" "a_PREP Hp_NPROP" :cr)
(-> "on_N line_N" "online_ADJ" )
(-> "linha_N Hp_N" "linha_N Hp_NPROP" :cr)
(-> "unicamp_N" "unicamp_NPROP" )
(-> "vice_N e_N versa_N" "vice_N e_KC versa_N" )
(-> "óculos_N 3_N D_N" "óculos_N 3_N D_N" :typo)
(-> "rapaz_N ñtricolor_N declaradoñ_N" "rapaz_N tricolor_ADJ declarado_V" :cr)
(-> "Ser_N ou_N não_N ser_N ..._N" "Ser_V ou_KC não_ADV ser_V ..._..." )
(-> "Mas_N César_N é_N um_N homem_N onrado_N ..._N" "Mas_KC César_NPROP é_V um_ART homem_N onrado_ADJ ..._..." )
(-> "beco_N sem_N saída_N" "beco_N sem_PREP saída_N" )
(-> "Botafogo_N X_N Inter_N" "Botafogo_NPROP X_N Inter_NPROP" :cr)
(-> "combinação_N dsa_N tenor_N" "combinação_N dsa_PREP tenor_N" :cr :typo)
(-> "Hora_N extra_N Editoria_N" "Hora_N extra_ADJ Editoria_N" :cr)
(-> "café_N da_N manhã_N" "café_N de_PREP a_ART manhã_N" )
(-> "Chegada_N a_PREP um_ART" "Chegada_ADJ a_PREP um_ART" )
(-> "Cantor_N prova_N estar_V" "Cantor_N prova_V estar_V" :cr)
(-> "por_N" "por_PREP" :cr)
(-> "teatro_N da_N morte_N" "teatro_N de_PREP a_ART morte_N" )
(-> "Haroldo_N Acton_N" "Haroldo_NPROP Acton_NPROP" :cr)
(-> "filmagens_N entraram_N V_N PREP_N final_ADJ" "filmagens_N entraram_V final_ADJ" :cr)
(-> "Caramelo_N Rigattoni_N Cocar_N" "Caramelo_NPROP Rigattoni_NPROP Cocar_NPROP" :cr)
(-> "ministro_N da_N Fazenda_N" "ministro_N de_PREP a_ART Fazenda_N" )
(-> "ângulos_N ñdo_N tratamento_N" "ângulos_N de_PREP o_ART tratamento_N" :cr)
(-> "mico-leão_N da_N cara-dourada_N" "mico-leão_N de_PREP a_ART cara-dourada_N" )
(-> "negócio_N da_N China_N" "negócio_N de_PREP a_ART China_N" )
(-> "ataca_N anualmente_ADV" "ataca_V anualmente_ADV" :cr)
(-> "Pesquisa_N mostra_N" "Pesquisa_N mostra_V" :cr)
(-> "Fun_N by_N Phone_N" "Fun_NPROP by_NPROP Phone_NPROP" :cr)
(-> "Pega_N Ladrão_N" "Pega_V Ladrão_N" :cr )
(-> "A_N inveja_N é_N uma_N merda_N" "A_ART inveja_N é_V uma_ART merda_N" )
(-> "Os_ART moedeiros_N falsos_N" "Os_ART moedeiros_N falsos_ADJ" :cr)
(-> "papel_N higiênico_N" "papel_N higiênico_ADJ" )
(-> "Filhos_N da_N puta_N" "Filhos_N de_PREP a_ART puta_N" )
(-> "fala_V de_PREP arte_N e_N KCítica_N" "fala_V de_PREP arte_N e_KC KCítica_N" :cr :typo)
(-> "serviço_N secreto_N israelense_N" "serviço_N secreto_ADJ israelense_ADJ" )
(-> "livre_N e_N justa_N" "livre_ADJ e_KC justa_ADJ" )
(-> "grande_ADJ triunfo_N israelo_N palestino_N" "grande_ADJ triunfo_N israelo_ADJ palestino_ADJ" :cr)
(-> "Ficção_N científica_N" "Ficção_N científica_ADJ" :cr)
(-> "não_N pagamento_N" "não_ADV pagamento_N" :cr)
(-> "secretário_N nacional_N de_N turismo_N e_N Serviços_N" "secretário_N nacional_ADJ de_PREP turismo_N e_KC Serviços_N" )
(-> "dia_N 23_N passado_N" "dia_N 23_N passado_ADJ" :cr)
(-> "dia_N a_N dia_N" "dia_N a_PREP dia_N" )
(-> "fertilização_N in_N vitro_N" "fertilização_N in_PREP vitro_N" :cr )
(-> "Discagem_N Direta_N à_N Distância_N" "Discagem_N Direta_ADJ a_PREP a_ART Distância_N" :cr )
(-> "analisado_V 2ª_N feira_N feira_N" "analisado_V 2ª_N feira_N feira_N" :typo)
(-> "os_ART chamados_N shopping_N centers_N" "os_ART chamados_V shopping_N centers_N" )
(-> "processadores_N Alpha_N AXP_N" "processadores_N Alpha_NPROP AXP_NPROP" :cr)
(-> "Centro_N Brasileiro_N de_N Filosofia_N para_N Crianças_N" "Centro_N Brasileiro_ADJ de_PREP Filosofia_N para_PREP Crianças_N" )
(-> "x_N" "x_SYM" :cr )
(-> "X_N" "X_SYM" :cr )
(-> "cadeirinhas_N ño_PROSUB" "cadeirinhas_N o_ART" :cr)
(-> "mil_NUM ñque_PRO-KS-REL" "mil_NUM que_PRO-KS-REL" :cr)
(-> "juros_N ño_PROSUB" "juros_N o_ART" :cr)
(-> "rapaz_N ñtricolor_N declaradoñ_N" "rapaz_N ñtricolor_ADJ declarado_V" :cr :typo)
(-> "ñonde_V moram_V" "onde_ADV-KS-REL moram_V" :cr)
(-> "ñou_N melhor_ADJ ,_, olheirasñ_N" "ou_KC melhor_ADJ ,_, olheiras_N" :cr)
(-> "ñsua_ADJ colega_N" "sua_PROADJ colega_N" :cr)
(-> "ñalternadamenteñ_N por_PREP" "alternadamente_ADV por_PREP" :cr)
(-> "ñclaroñ_N a_PROADJ" "claro_N a_PROADJ" :cr)
(-> "ñsem_PREP música_N" "sem_PREP música_N" :cr)
(-> "ñnem_KC abundam_V" "nem_KC abundam_V" :cr)
(-> "ñenquanto_N quadriplica_V" "enquanto_KS quadriplica_V" :cr)
(-> "ñdistanteñ_N de_PREP" "distante_N de_PREP" :cr)
(-> "ñentre_V eles_PROPESS um_ART Di_NPROP Cavalcantiñ_NPROP" "entre_V eles_PROPESS um_ART Di_NPROP Cavalcanti_NPROP" :cr)
(-> "ñque_V enfrenta_V ventos_N contra_ADV em_PREP o_ART setor_N cofreñ_N" "que_V enfrenta_V ventos_N contra_ADV em_PREP o_ART setor_N cofre_N" :cr)
(-> "ñmas_N pra_PREP" "mas_N pra_PREP" :cr)
(-> "ñcom_N direção_N" "com_PREP direção_N" :cr)
(-> "ñpasmemñ_N nunca_ADV" "pasmem_V nunca_ADV" :cr)
(-> "ñespecialmente_ADV de_PREP" "especialmente_ADV de_PREP" :cr)
(-> "ñda_N geração_N" "de_PREP a_ART geração_N" :cr)
(-> "ñpor_N que_KS" "por_PREP que_KS" :cr)
(-> "ñdo_N tratamento_N" "de_PREP o_N tratamento_N" :cr)
(-> "Capote_," "Capote_NPROP" :cr)
(-> "Z-Note_NPOP" "Z-Note_NPROP" :cr)
(-> "NPROP,_," "" :cr)
(-> "-_-" "-_PUNCT" :cr)
(-> "((_((" "((_PUNCT" :cr)
(-> "))_))" "))_PUNCT" :cr)
(-> "`_`" "`_PUNCT" :cr)
(-> "$_$" "$_SYM" :cr)
(-> "\(260\,_NUM" "\(_PUNCT 260_NUM \,_PUNCT" :cr)
(-> "=_=" "=_SYM" :cr)

;; linguas estrangeiras
(-> "maître_N à_N penser_N" "maître_X à_X penser_X" :cr)
(-> "Encadernadoras_N first_N class_N" "Encadernadoras_N first_X class_X" :cr)
(-> "white_N anglo-saxon_N protestant_N" "white_X anglo-saxon_X protestant_X" :cr)
(-> "made_N in_N Brazil_N" "made_N in_N Brazil_X" :cr)
(-> "marca_N high_N class_N" "marca_N high_X class_X" :cr )
(-> "mensagem_N SUBSCRIBE_N Mini-JIR_N" "mensagem_N SUBSCRIBE_X Mini-JIR_X" :cr )
(-> "blue_N jets_N jets_N" "blue_X jets_X" :cr)
(-> "ne_N plus_N ultra_N" "ne_X plus_X ultra_X" :cr)
(-> "white_N man'_N s_N nigger_N" "white_X man's_X nigger_X" :cr)
(-> "death_N by_N water_N" "death_X by_X water_X" :cr)
(-> "The_N tarantula_N rattling_N" "The_X tarantula_X rattling_X" :cr)
(-> "I_N walk_N on_N fire_N" "I_X walk_X on_X fire_X" :cr)
(-> "minimal_N pairs_N pairs_N" "minimal_X pairs_X" :cr)
(-> "law_N and_N economics_N" "law_X and_X economics_X" :cr)
(-> "pay_N for_N performance_N" "pay_X for_X performance_X" :cr)
(-> "Prime_N rate_N" "Prime_X rate_X" :cr)
(-> "running_N back_N back_N" "running_X back_X" :cr)
(-> "Siempre_N com_N la_N surda_N" "Siempre_X com_X la_X surda_X" :cr)
(-> "Maradonariz_N go_N home_N" "Maradonariz_X go_X home_X" :cr)
(-> "Maradona_N Fails_N Drug_N Test_N" "Maradona_X Fails_X Drug_X Test_X" :cr)
(-> "Freud_NPROP traduziu_V l'_N âme_N humaine_N por_PREP menschlicher_N Geist_N" "Freud_NPROP traduziu_V l'_X âme_X humaine_X por_PREP menschlicher_X Geist_X" :cr)
(-> "psychologie_N nouvelle_N por_PREP neue_N Seele_N ,_, conditions_N mentales_N por_PREP Seelenzustand_N" "psychologie_X nouvelle_X por_PREP neue_X Seele_X ,_, conditions_X mentales_X por_PREP Seelenzustand_X" :cr)
(-> "l'_N organe_N psychique_N por_PREP Seelenorgan_N" "l'_X organe_X psychique_X por_PREP Seelenorgan_X" :cr)
(-> "encontramos_V Beziehung_N von_N Leiblichem_N un_N Seelischem_N para_PREP psycho-physical_N relation_N relation_N" "encontramos_V Beziehung_X von_X Leiblichem_X un_X Seelischem_X para_PREP psycho-physical_X relation_X" :cr)
(-> "Appareil_N d'_N âme_N ,_, como_PREP versão_N de_PREP Seelenapparat_N" "Appareil_X d'_X âme_X ,_, como_PREP versão_N de_PREP Seelenapparat_X" :cr)
(-> "manifester_N Trauminhalt_N é_VAUX vertido_V como_PREP contenu_N du_N rêve_N manifeste_N" "manifester_X Trauminhalt_X é_VAUX vertido_V como_PREP contenu_X du_X rêve_X manifeste_X" :cr)
(-> "katà_N phréna_ADJ kaì_N katà_N thymón_N" "katà_X phréna_X kaì_X katà_X thymón_X" :cr)
(-> "And_N The_N Oscar_N GOES_N" "And_X The_X Oscar_X GOES_X" :cr)
(-> "work_N in_N progress_N" "work_X in_X progress_X" :cr)
(-> "up_N to_N date_N" "up_X to_X date_X" :cr)
(-> "made_N in_N" "made_X in_X" :cr)
(-> "NOT_N FAIR_N" "NOT_X FAIR_X" :cr)
(-> "top_N beauty_N artist_N" "top_X beauty_X artist_X" :cr)
(-> "drags_N e_N dykes_N on_N bikes_N" "drags_N e_KC dykes_N on_X bikes_X" :cr)
(-> "up_N up_N away_N" "up_X up_X away_X" :cr)
(-> "Ooh_N aah_N Wonderbra_N" "Ooh_X aah_X Wonderbra_X" :cr)
(-> "Cup_N fever_N" "Cup_X fever_X" :cr)
(-> "carpal_N tunnel_N syndrome_N" "carpal_X tunnel_X syndrome_X" :cr)
(-> "me_N a_N non_N troppo_N" "me_X a_X non_X troppo_X" :cr)
(-> "personal_N digital_N assistant_N" "personal_X digital_X assistant_X" :cr)
(r-> "(\\w+)_ART PREP\\|\\+_ART" "\\1_PREP" :cr)
(-> "quorum\\|_N" "quorum_N" :cr)

(-> "até_PART" "até_PREP" )
(-> "Até_PART" "Até_PREP" )


;; OUTRAS REGRAS
(r-> "(\\w+)_ART (\\w+)_ADJ (\\w+)_([^N])" "\\1_ART \\2_N \\3_\\4")

;; para evitar que 1000_NUM seja matched com a regra abaixo,
;; temos que dizer que _N e' seguido de um ou mais espacos.
(r-> "(\\s+)([\\d\\,\\.\\º\\-\\/]+)_N(\\s+)" "\\1\\2_NUM\\3")

;; a regra acima nao funciona se _N for a ultima coisa na linha.
;; Esta regra abaixo serve pra isso:
(r-> "([\\d\\,\\.\\º\\-\\/]+)_N$" "\\1_NUM")

(r-> "(ADJ|PREP|ADV|VAUX|KC|ART|PROADJ|IN|N|NUM|PROPESS|PROSUB|NPROP|PU|KS|PRO-KS|PRO-KS-REL|ADV-KS|ADV-KS-REL|CUR|V|PCP|PDEN)_(SCONJ|DET|ADJ|PREP|ADV|VAUX|KC|ART|PROADJ|IN|N|NUM|PROPESS|PROSUB|NPROP|PU|KS|PRO-KS|PRO-KS-REL|ADV-KS|ADV-KS-REL|CUR|V|PCP|PDEN)" "" :cr)

(-> "%_NUM" "%_SYM" )
(-> "%_N" "%_SYM" )
(-> ":_:" ":_PUNCT" )
(-> "!_!" "!_PUNCT" )
(-> "?_?" "?_PUNCT" )
(-> ";_;" ";_PUNCT" )
(-> ",_," ",_PUNCT" )
(-> "._." "._PUNCT" )
(-> "..._..." "..._PUNCT" )
(-> "(_(" "\(_PUNCT" )
(-> ")_)" "\)_PUNCT" )
(-> "[_[" "\[_PUNCT" )
(-> "]_]" "\]_PUNCT" )
(-> "{_{" "\{_PUNCT" )
(-> "}_}" "\}_PUNCT" )
(-> "\\\\_\\\\" "\\\\_PUNCT" )
(-> "/_/" "\/_PUNCT" )
(-> "<_<" "\<_PUNCT" )
(-> ">_>" "\>_PUNCT" )
(-> "\"\_\"" "\"_PUNCT" )
(-> "\'\_\'" "\'_PUNCT" )
(-> "*_PDEN" "*_ADV" )
(-> "*_PREP" "*_ADP" )
(-> "*_VAUX" "*_AUX" )
(-> "*_KC" "*_CONJ" )
(-> "*_ART" "*_DET" )
(-> "*_PROADJ" "*_DET" )
(-> "*_IN" "*_INTJ" )
(-> "*_NPROP" "*_PROPN" )
(-> "*_PROPESS" "*_PRON" )
(-> "*_PROSUB" "*_PRON" )
(-> "*_PRO-KS-REL" "*_SCONJ" )
(-> "*_PRO-KS" "*_SCONJ" )
(-> "*_ADV-KS-REL" "*_SCONJ" )
(-> "*_ADV-KS" "*_SCONJ" )
(-> "*_KS" "*_SCONJ" )
(-> "*_CUR" "*_SYM" )
(-> "*_V" "*_VERB" )
(-> "*_N" "*_NOUN" )
(-> "*_NOUNUM" "*_NUM" )
(-> "*_DET PREP\\|\\+_DET" "*_ADP" :cr)
